// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collection.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFollowUp = `-- name: GetFollowUp :one
select id, receivable_id, followup_type, notes, performed_at, performed_by_user_id, next_action_on, created_at
from receivables.collection_followups
where organization_id = $1 and id = $2
`

type GetFollowUpParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetFollowUpRow struct {
	ID                uuid.UUID
	ReceivableID      uuid.UUID
	FollowupType      string
	Notes             string
	PerformedAt       time.Time
	PerformedByUserID uuid.NullUUID
	NextActionOn      pgtype.Date
	CreatedAt         time.Time
}

func (q *Queries) GetFollowUp(ctx context.Context, arg GetFollowUpParams) (GetFollowUpRow, error) {
	row := q.db.QueryRow(ctx, getFollowUp, arg.OrganizationID, arg.ID)
	var i GetFollowUpRow
	err := row.Scan(
		&i.ID,
		&i.ReceivableID,
		&i.FollowupType,
		&i.Notes,
		&i.PerformedAt,
		&i.PerformedByUserID,
		&i.NextActionOn,
		&i.CreatedAt,
	)
	return i, err
}

const getPromise = `-- name: GetPromise :one
select id, receivable_id, followup_id, trim_scale(promised_amount)::text as promised_amount, promised_on, status,
       created_by_user_id, created_at, updated_at
from receivables.payment_promises
where organization_id = $1 and id = $2
`

type GetPromiseParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetPromiseRow struct {
	ID              uuid.UUID
	ReceivableID    uuid.UUID
	FollowupID      uuid.NullUUID
	PromisedAmount  string
	PromisedOn      pgtype.Date
	Status          string
	CreatedByUserID uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetPromise(ctx context.Context, arg GetPromiseParams) (GetPromiseRow, error) {
	row := q.db.QueryRow(ctx, getPromise, arg.OrganizationID, arg.ID)
	var i GetPromiseRow
	err := row.Scan(
		&i.ID,
		&i.ReceivableID,
		&i.FollowupID,
		&i.PromisedAmount,
		&i.PromisedOn,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFollowUp = `-- name: InsertFollowUp :exec

insert into receivables.collection_followups (
  id, organization_id, receivable_id, followup_type, notes, performed_at, performed_by_user_id, next_action_on
) values (
  $1, $2, $3, $4, $5,
  $6, $7, $8
)
`

type InsertFollowUpParams struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	ReceivableID      uuid.UUID
	FollowupType      string
	Notes             string
	PerformedAt       time.Time
	PerformedByUserID uuid.NullUUID
	NextActionOn      pgtype.Date
}

// Seguimientos y promesas de pago. Son historial de cobranza: se crean y una promesa cambia de estado; no se borran.
func (q *Queries) InsertFollowUp(ctx context.Context, arg InsertFollowUpParams) error {
	_, err := q.db.Exec(ctx, insertFollowUp,
		arg.ID,
		arg.OrganizationID,
		arg.ReceivableID,
		arg.FollowupType,
		arg.Notes,
		arg.PerformedAt,
		arg.PerformedByUserID,
		arg.NextActionOn,
	)
	return err
}

const insertPromise = `-- name: InsertPromise :exec
insert into receivables.payment_promises (
  id, organization_id, receivable_id, followup_id, promised_amount, promised_on, created_by_user_id
) values (
  $1, $2, $3, $4,
  $5::text::numeric, $6, $7
)
`

type InsertPromiseParams struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	ReceivableID    uuid.UUID
	FollowupID      uuid.NullUUID
	PromisedAmount  string
	PromisedOn      pgtype.Date
	CreatedByUserID uuid.NullUUID
}

func (q *Queries) InsertPromise(ctx context.Context, arg InsertPromiseParams) error {
	_, err := q.db.Exec(ctx, insertPromise,
		arg.ID,
		arg.OrganizationID,
		arg.ReceivableID,
		arg.FollowupID,
		arg.PromisedAmount,
		arg.PromisedOn,
		arg.CreatedByUserID,
	)
	return err
}

const listFollowUps = `-- name: ListFollowUps :many
select id, receivable_id, followup_type, notes, performed_at, performed_by_user_id, next_action_on, created_at
from receivables.collection_followups
where organization_id = $1 and receivable_id = $2
order by performed_at desc, id desc
limit 200
`

type ListFollowUpsParams struct {
	OrganizationID uuid.UUID
	ReceivableID   uuid.UUID
}

type ListFollowUpsRow struct {
	ID                uuid.UUID
	ReceivableID      uuid.UUID
	FollowupType      string
	Notes             string
	PerformedAt       time.Time
	PerformedByUserID uuid.NullUUID
	NextActionOn      pgtype.Date
	CreatedAt         time.Time
}

func (q *Queries) ListFollowUps(ctx context.Context, arg ListFollowUpsParams) ([]ListFollowUpsRow, error) {
	rows, err := q.db.Query(ctx, listFollowUps, arg.OrganizationID, arg.ReceivableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowUpsRow{}
	for rows.Next() {
		var i ListFollowUpsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReceivableID,
			&i.FollowupType,
			&i.Notes,
			&i.PerformedAt,
			&i.PerformedByUserID,
			&i.NextActionOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromises = `-- name: ListPromises :many
select id, receivable_id, followup_id, trim_scale(promised_amount)::text as promised_amount, promised_on, status,
       created_by_user_id, created_at, updated_at
from receivables.payment_promises
where organization_id = $1 and receivable_id = $2
order by promised_on desc, id desc
limit 200
`

type ListPromisesParams struct {
	OrganizationID uuid.UUID
	ReceivableID   uuid.UUID
}

type ListPromisesRow struct {
	ID              uuid.UUID
	ReceivableID    uuid.UUID
	FollowupID      uuid.NullUUID
	PromisedAmount  string
	PromisedOn      pgtype.Date
	Status          string
	CreatedByUserID uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListPromises(ctx context.Context, arg ListPromisesParams) ([]ListPromisesRow, error) {
	rows, err := q.db.Query(ctx, listPromises, arg.OrganizationID, arg.ReceivableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPromisesRow{}
	for rows.Next() {
		var i ListPromisesRow
		if err := rows.Scan(
			&i.ID,
			&i.ReceivableID,
			&i.FollowupID,
			&i.PromisedAmount,
			&i.PromisedOn,
			&i.Status,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPromise = `-- name: LockPromise :one
select id, receivable_id, followup_id, trim_scale(promised_amount)::text as promised_amount, promised_on, status,
       created_by_user_id, created_at, updated_at
from receivables.payment_promises
where organization_id = $1 and id = $2
for update
`

type LockPromiseParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type LockPromiseRow struct {
	ID              uuid.UUID
	ReceivableID    uuid.UUID
	FollowupID      uuid.NullUUID
	PromisedAmount  string
	PromisedOn      pgtype.Date
	Status          string
	CreatedByUserID uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) LockPromise(ctx context.Context, arg LockPromiseParams) (LockPromiseRow, error) {
	row := q.db.QueryRow(ctx, lockPromise, arg.OrganizationID, arg.ID)
	var i LockPromiseRow
	err := row.Scan(
		&i.ID,
		&i.ReceivableID,
		&i.FollowupID,
		&i.PromisedAmount,
		&i.PromisedOn,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePromiseStatus = `-- name: UpdatePromiseStatus :execrows
update receivables.payment_promises
set status = $1
where organization_id = $2 and id = $3 and status = 'pending'
`

type UpdatePromiseStatusParams struct {
	Status         string
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) UpdatePromiseStatus(ctx context.Context, arg UpdatePromiseStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePromiseStatus, arg.Status, arg.OrganizationID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
