// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const claimInboxMessage = `-- name: ClaimInboxMessage :execrows

insert into integration.inbox_messages (consumer_service, event_id, event_type, organization_id)
values ('receivables', $1, $2, $3)
on conflict (consumer_service, event_id) do nothing
`

type ClaimInboxMessageParams struct {
	EventID        uuid.UUID
	EventType      string
	OrganizationID uuid.UUID
}

// Consumo de eventos (ADR 0005). consumer_service fijo: la política inbox_messages_service exige que coincida con
// shared.current_service() y el login de este servicio solo puede ser 'receivables'.
// Reclama el evento. 0 filas = duplicado: otro intento ya lo procesó y confirmó.
func (q *Queries) ClaimInboxMessage(ctx context.Context, arg ClaimInboxMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimInboxMessage, arg.EventID, arg.EventType, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertDeadLetter = `-- name: InsertDeadLetter :exec
insert into integration.dead_letters (
  consumer_service, event_id, event_type, organization_id, payload, error_message, attempts
) values (
  'receivables', $1, $2, $3,
  $4::text::jsonb, $5, $6
)
`

type InsertDeadLetterParams struct {
	EventID        uuid.UUID
	EventType      string
	OrganizationID uuid.NullUUID
	Payload        string
	ErrorMessage   string
	Attempts       int32
}

// payload como texto (ADR 0004 de Platform: con QueryExecModeExec un []byte viajaría como bytea).
func (q *Queries) InsertDeadLetter(ctx context.Context, arg InsertDeadLetterParams) error {
	_, err := q.db.Exec(ctx, insertDeadLetter,
		arg.EventID,
		arg.EventType,
		arg.OrganizationID,
		arg.Payload,
		arg.ErrorMessage,
		arg.Attempts,
	)
	return err
}

const markInboxProcessed = `-- name: MarkInboxProcessed :exec
update integration.inbox_messages
   set processed_at = now()
 where consumer_service = 'receivables' and event_id = $1
`

func (q *Queries) MarkInboxProcessed(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInboxProcessed, eventID)
	return err
}
