// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getApplication = `-- name: GetApplication :one
select id, payment_id, receivable_id, amount::text as amount, applied_at, applied_by_user_id,
       reversed_at, reversed_by_user_id, reversal_reason
from receivables.payment_applications
where organization_id = $1 and id = $2
`

type GetApplicationParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetApplicationRow struct {
	ID               uuid.UUID
	PaymentID        uuid.UUID
	ReceivableID     uuid.UUID
	Amount           string
	AppliedAt        time.Time
	AppliedByUserID  uuid.NullUUID
	ReversedAt       pgtype.Timestamptz
	ReversedByUserID uuid.NullUUID
	ReversalReason   pgtype.Text
}

func (q *Queries) GetApplication(ctx context.Context, arg GetApplicationParams) (GetApplicationRow, error) {
	row := q.db.QueryRow(ctx, getApplication, arg.OrganizationID, arg.ID)
	var i GetApplicationRow
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.ReceivableID,
		&i.Amount,
		&i.AppliedAt,
		&i.AppliedByUserID,
		&i.ReversedAt,
		&i.ReversedByUserID,
		&i.ReversalReason,
	)
	return i, err
}

const getReceivableState = `-- name: GetReceivableState :one
select balance_amount::text as balance_amount, status, settled_at
from receivables.receivables
where organization_id = $1 and id = $2
`

type GetReceivableStateParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetReceivableStateRow struct {
	BalanceAmount string
	Status        string
	SettledAt     pgtype.Timestamptz
}

// Lo que dejaron los triggers, para compararlo con el agregado.
func (q *Queries) GetReceivableState(ctx context.Context, arg GetReceivableStateParams) (GetReceivableStateRow, error) {
	row := q.db.QueryRow(ctx, getReceivableState, arg.OrganizationID, arg.ID)
	var i GetReceivableStateRow
	err := row.Scan(&i.BalanceAmount, &i.Status, &i.SettledAt)
	return i, err
}

const insertAdjustment = `-- name: InsertAdjustment :exec
insert into receivables.receivable_adjustments (
  id, organization_id, receivable_id, adjustment_type, source_document_id, source_event_id, amount, reason,
  created_by_user_id
) values (
  $1, $2, $3, $4,
  $5, $6, $7::text::numeric, $8,
  $9
)
`

type InsertAdjustmentParams struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	ReceivableID     uuid.UUID
	AdjustmentType   string
	SourceDocumentID uuid.NullUUID
	SourceEventID    uuid.NullUUID
	Amount           string
	Reason           string
	CreatedByUserID  uuid.NullUUID
}

// receivable_adjustments_apply recalcula saldo y estado.
func (q *Queries) InsertAdjustment(ctx context.Context, arg InsertAdjustmentParams) error {
	_, err := q.db.Exec(ctx, insertAdjustment,
		arg.ID,
		arg.OrganizationID,
		arg.ReceivableID,
		arg.AdjustmentType,
		arg.SourceDocumentID,
		arg.SourceEventID,
		arg.Amount,
		arg.Reason,
		arg.CreatedByUserID,
	)
	return err
}

const insertApplication = `-- name: InsertApplication :exec
insert into receivables.payment_applications (
  id, organization_id, payment_id, receivable_id, amount, applied_at, applied_by_user_id
) values (
  $1, $2, $3, $4,
  $5::text::numeric, $6, $7
)
`

type InsertApplicationParams struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	PaymentID       uuid.UUID
	ReceivableID    uuid.UUID
	Amount          string
	AppliedAt       time.Time
	AppliedByUserID uuid.NullUUID
}

// payment_applications_validate revisa cliente, moneda, pago anulado, cuenta anulada y suma aplicada, y recalcula.
func (q *Queries) InsertApplication(ctx context.Context, arg InsertApplicationParams) error {
	_, err := q.db.Exec(ctx, insertApplication,
		arg.ID,
		arg.OrganizationID,
		arg.PaymentID,
		arg.ReceivableID,
		arg.Amount,
		arg.AppliedAt,
		arg.AppliedByUserID,
	)
	return err
}

const insertPayment = `-- name: InsertPayment :exec
insert into receivables.payments (
  id, organization_id, customer_id, received_on, amount, currency_code, exchange_rate, payment_method_code,
  reference, notes, received_by_user_id
) values (
  $1, $2, $3, $4,
  $5::text::numeric, $6::text, $7::text::numeric,
  $8, $9, $10, $11
)
`

type InsertPaymentParams struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	CustomerID        uuid.UUID
	ReceivedOn        pgtype.Date
	Amount            string
	CurrencyCode      string
	ExchangeRate      string
	PaymentMethodCode string
	Reference         pgtype.Text
	Notes             pgtype.Text
	ReceivedByUserID  uuid.NullUUID
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) error {
	_, err := q.db.Exec(ctx, insertPayment,
		arg.ID,
		arg.OrganizationID,
		arg.CustomerID,
		arg.ReceivedOn,
		arg.Amount,
		arg.CurrencyCode,
		arg.ExchangeRate,
		arg.PaymentMethodCode,
		arg.Reference,
		arg.Notes,
		arg.ReceivedByUserID,
	)
	return err
}

const listActivePaymentIDsForReceivable = `-- name: ListActivePaymentIDsForReceivable :many
select distinct payment_id
from receivables.payment_applications
where organization_id = $1 and receivable_id = $2 and reversed_at is null
order by payment_id
`

type ListActivePaymentIDsForReceivableParams struct {
	OrganizationID uuid.UUID
	ReceivableID   uuid.UUID
}

// Pagos con aplicaciones vigentes en la cuenta, sin bloquear: sirve para bloquearlos antes que la cuenta.
func (q *Queries) ListActivePaymentIDsForReceivable(ctx context.Context, arg ListActivePaymentIDsForReceivableParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActivePaymentIDsForReceivable, arg.OrganizationID, arg.ReceivableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var payment_id uuid.UUID
		if err := rows.Scan(&payment_id); err != nil {
			return nil, err
		}
		items = append(items, payment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentApplications = `-- name: ListPaymentApplications :many
select id, payment_id, receivable_id, amount::text as amount, applied_at, applied_by_user_id,
       reversed_at, reversed_by_user_id, reversal_reason
from receivables.payment_applications
where organization_id = $1 and payment_id = $2
order by applied_at, id
`

type ListPaymentApplicationsParams struct {
	OrganizationID uuid.UUID
	PaymentID      uuid.UUID
}

type ListPaymentApplicationsRow struct {
	ID               uuid.UUID
	PaymentID        uuid.UUID
	ReceivableID     uuid.UUID
	Amount           string
	AppliedAt        time.Time
	AppliedByUserID  uuid.NullUUID
	ReversedAt       pgtype.Timestamptz
	ReversedByUserID uuid.NullUUID
	ReversalReason   pgtype.Text
}

func (q *Queries) ListPaymentApplications(ctx context.Context, arg ListPaymentApplicationsParams) ([]ListPaymentApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listPaymentApplications, arg.OrganizationID, arg.PaymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentApplicationsRow{}
	for rows.Next() {
		var i ListPaymentApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.ReceivableID,
			&i.Amount,
			&i.AppliedAt,
			&i.AppliedByUserID,
			&i.ReversedAt,
			&i.ReversedByUserID,
			&i.ReversalReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivableAdjustments = `-- name: ListReceivableAdjustments :many
select id, adjustment_type, amount::text as amount, source_document_id, source_event_id, reason,
       created_by_user_id, created_at
from receivables.receivable_adjustments
where organization_id = $1 and receivable_id = $2
order by created_at, id
`

type ListReceivableAdjustmentsParams struct {
	OrganizationID uuid.UUID
	ReceivableID   uuid.UUID
}

type ListReceivableAdjustmentsRow struct {
	ID               uuid.UUID
	AdjustmentType   string
	Amount           string
	SourceDocumentID uuid.NullUUID
	SourceEventID    uuid.NullUUID
	Reason           string
	CreatedByUserID  uuid.NullUUID
	CreatedAt        time.Time
}

func (q *Queries) ListReceivableAdjustments(ctx context.Context, arg ListReceivableAdjustmentsParams) ([]ListReceivableAdjustmentsRow, error) {
	rows, err := q.db.Query(ctx, listReceivableAdjustments, arg.OrganizationID, arg.ReceivableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReceivableAdjustmentsRow{}
	for rows.Next() {
		var i ListReceivableAdjustmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdjustmentType,
			&i.Amount,
			&i.SourceDocumentID,
			&i.SourceEventID,
			&i.Reason,
			&i.CreatedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivableApplications = `-- name: ListReceivableApplications :many
select id, payment_id, receivable_id, amount::text as amount, applied_at, applied_by_user_id,
       reversed_at, reversed_by_user_id, reversal_reason
from receivables.payment_applications
where organization_id = $1 and receivable_id = $2
order by applied_at, id
`

type ListReceivableApplicationsParams struct {
	OrganizationID uuid.UUID
	ReceivableID   uuid.UUID
}

type ListReceivableApplicationsRow struct {
	ID               uuid.UUID
	PaymentID        uuid.UUID
	ReceivableID     uuid.UUID
	Amount           string
	AppliedAt        time.Time
	AppliedByUserID  uuid.NullUUID
	ReversedAt       pgtype.Timestamptz
	ReversedByUserID uuid.NullUUID
	ReversalReason   pgtype.Text
}

func (q *Queries) ListReceivableApplications(ctx context.Context, arg ListReceivableApplicationsParams) ([]ListReceivableApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listReceivableApplications, arg.OrganizationID, arg.ReceivableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReceivableApplicationsRow{}
	for rows.Next() {
		var i ListReceivableApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.ReceivableID,
			&i.Amount,
			&i.AppliedAt,
			&i.AppliedByUserID,
			&i.ReversedAt,
			&i.ReversedByUserID,
			&i.ReversalReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPayment = `-- name: LockPayment :one
select id, customer_id, received_on, amount::text as amount, currency_code::text as currency_code,
       exchange_rate::text as exchange_rate, payment_method_code, reference, notes, status, void_reason, voided_at,
       received_by_user_id, created_at
from receivables.payments
where organization_id = $1 and id = $2
for update
`

type LockPaymentParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type LockPaymentRow struct {
	ID                uuid.UUID
	CustomerID        uuid.UUID
	ReceivedOn        pgtype.Date
	Amount            string
	CurrencyCode      string
	ExchangeRate      string
	PaymentMethodCode string
	Reference         pgtype.Text
	Notes             pgtype.Text
	Status            string
	VoidReason        pgtype.Text
	VoidedAt          pgtype.Timestamptz
	ReceivedByUserID  uuid.NullUUID
	CreatedAt         time.Time
}

func (q *Queries) LockPayment(ctx context.Context, arg LockPaymentParams) (LockPaymentRow, error) {
	row := q.db.QueryRow(ctx, lockPayment, arg.OrganizationID, arg.ID)
	var i LockPaymentRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ReceivedOn,
		&i.Amount,
		&i.CurrencyCode,
		&i.ExchangeRate,
		&i.PaymentMethodCode,
		&i.Reference,
		&i.Notes,
		&i.Status,
		&i.VoidReason,
		&i.VoidedAt,
		&i.ReceivedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const lockReceivable = `-- name: LockReceivable :one

select id, source_invoice_id, customer_id, customer_legal_name, document_number,
       currency_code::text as currency_code, original_amount::text as original_amount,
       balance_amount::text as balance_amount, issued_on, due_on, status, settled_at, created_at
from receivables.receivables
where organization_id = $1 and id = $2
for update
`

type LockReceivableParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type LockReceivableRow struct {
	ID                uuid.UUID
	SourceInvoiceID   uuid.UUID
	CustomerID        uuid.UUID
	CustomerLegalName string
	DocumentNumber    string
	CurrencyCode      string
	OriginalAmount    string
	BalanceAmount     string
	IssuedOn          pgtype.Date
	DueOn             pgtype.Date
	Status            string
	SettledAt         pgtype.Timestamptz
	CreatedAt         time.Time
}

// Carga y persistencia de los agregados (ADR 0006). Toda consulta filtra por organization_id además de RLS.
// Los montos viajan como texto: nunca pasan por float. Saldo y estado nunca se escriben: los recalcula la base.
// Bloquea la cuenta. El orden de bloqueo lo decide el caso de uso: pagos por id y después cuentas por id.
func (q *Queries) LockReceivable(ctx context.Context, arg LockReceivableParams) (LockReceivableRow, error) {
	row := q.db.QueryRow(ctx, lockReceivable, arg.OrganizationID, arg.ID)
	var i LockReceivableRow
	err := row.Scan(
		&i.ID,
		&i.SourceInvoiceID,
		&i.CustomerID,
		&i.CustomerLegalName,
		&i.DocumentNumber,
		&i.CurrencyCode,
		&i.OriginalAmount,
		&i.BalanceAmount,
		&i.IssuedOn,
		&i.DueOn,
		&i.Status,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const reverseApplication = `-- name: ReverseApplication :execrows
update receivables.payment_applications
set reversed_at = $1, reversed_by_user_id = $2,
    reversal_reason = $3
where organization_id = $4 and id = $5 and reversed_at is null
`

type ReverseApplicationParams struct {
	ReversedAt       pgtype.Timestamptz
	ReversedByUserID uuid.NullUUID
	ReversalReason   pgtype.Text
	OrganizationID   uuid.UUID
	ID               uuid.UUID
}

// Una aplicación solo se revierte una vez (reversed_at is null) y nunca se borra.
func (q *Queries) ReverseApplication(ctx context.Context, arg ReverseApplicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, reverseApplication,
		arg.ReversedAt,
		arg.ReversedByUserID,
		arg.ReversalReason,
		arg.OrganizationID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const voidPayment = `-- name: VoidPayment :execrows
update receivables.payments
set status = 'voided', void_reason = $1, voided_at = $2
where organization_id = $3 and id = $4 and status = 'posted'
`

type VoidPaymentParams struct {
	VoidReason     pgtype.Text
	VoidedAt       pgtype.Timestamptz
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

// payments_guard exige que no queden aplicaciones vigentes.
func (q *Queries) VoidPayment(ctx context.Context, arg VoidPaymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, voidPayment,
		arg.VoidReason,
		arg.VoidedAt,
		arg.OrganizationID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
