// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditAuditEvent struct {
	ID             uuid.UUID
	OrganizationID uuid.NullUUID
	OccurredAt     time.Time
	Service        string
	ActorType      string
	ActorUserID    uuid.NullUUID
	Action         string
	EntityType     string
	EntityID       uuid.NullUUID
	CorrelationID  uuid.UUID
	IpAddress      *netip.Addr
	UserAgent      pgtype.Text
	Payload        []byte
}

type CoreOrganization struct {
	ID       uuid.UUID
	Timezone string
	Status   string
}

type CoreOrganizationUser struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	Status         string
}

type CoreOrganizationUserRole struct {
	OrganizationID     uuid.UUID
	OrganizationUserID uuid.UUID
	RoleCode           string
}

type CoreUser struct {
	ID              uuid.UUID
	ExternalSubject string
	Status          string
}

type IntegrationDeadLetter struct {
	ID               uuid.UUID
	ConsumerService  string
	EventID          uuid.UUID
	EventType        string
	OrganizationID   uuid.NullUUID
	Payload          []byte
	ErrorMessage     string
	Attempts         int32
	FailedAt         time.Time
	ResolvedAt       pgtype.Timestamptz
	ResolvedByUserID uuid.NullUUID
	ResolutionNotes  pgtype.Text
}

type IntegrationIdempotencyKey struct {
	Service        string
	OrganizationID uuid.UUID
	IdempotencyKey string
	RequestHash    string
	ResponseStatus pgtype.Int4
	ResponseBody   []byte
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

type IntegrationInboxMessage struct {
	ConsumerService string
	EventID         uuid.UUID
	EventType       string
	OrganizationID  uuid.UUID
	ReceivedAt      time.Time
	ProcessedAt     pgtype.Timestamptz
}

type IntegrationOutboxMessage struct {
	ID              uuid.UUID
	SourceService   string
	OrganizationID  uuid.UUID
	EventType       string
	EventVersion    int32
	AggregateType   string
	AggregateID     uuid.UUID
	CorrelationID   uuid.UUID
	Payload         []byte
	OccurredAt      time.Time
	PublishedAt     pgtype.Timestamptz
	PublishAttempts int32
	NextAttemptAt   pgtype.Timestamptz
	LastError       pgtype.Text
}

type ReceivablesCollectionFollowup struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	ReceivableID      uuid.UUID
	FollowupType      string
	Notes             string
	PerformedAt       time.Time
	PerformedByUserID uuid.NullUUID
	NextActionOn      pgtype.Date
	CreatedAt         time.Time
}

type ReceivablesPayment struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	CustomerID        uuid.UUID
	ReceivedOn        pgtype.Date
	Amount            interface{}
	CurrencyCode      interface{}
	ExchangeRate      interface{}
	PaymentMethodCode string
	Reference         pgtype.Text
	Notes             pgtype.Text
	Status            string
	VoidReason        pgtype.Text
	VoidedAt          pgtype.Timestamptz
	ReceivedByUserID  uuid.NullUUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ReceivablesPaymentApplication struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	PaymentID        uuid.UUID
	ReceivableID     uuid.UUID
	Amount           interface{}
	AppliedAt        time.Time
	AppliedByUserID  uuid.NullUUID
	ReversedAt       pgtype.Timestamptz
	ReversedByUserID uuid.NullUUID
	ReversalReason   pgtype.Text
}

type ReceivablesPaymentPromise struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	ReceivableID    uuid.UUID
	FollowupID      uuid.NullUUID
	PromisedAmount  interface{}
	PromisedOn      pgtype.Date
	Status          string
	CreatedByUserID uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ReceivablesReceivable struct {
	ID                           uuid.UUID
	OrganizationID               uuid.UUID
	SourceInvoiceID              uuid.UUID
	SourceEventID                uuid.UUID
	CustomerID                   uuid.UUID
	CustomerIdentificationNumber string
	CustomerLegalName            string
	DocumentNumber               string
	CurrencyCode                 interface{}
	OriginalAmount               interface{}
	BalanceAmount                interface{}
	IssuedOn                     pgtype.Date
	DueOn                        pgtype.Date
	SaleConditionCode            string
	Status                       string
	SettledAt                    pgtype.Timestamptz
	CreatedAt                    time.Time
	UpdatedAt                    time.Time
}

type ReceivablesReceivableAdjustment struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	ReceivableID     uuid.UUID
	AdjustmentType   string
	SourceDocumentID uuid.NullUUID
	SourceEventID    uuid.NullUUID
	Amount           interface{}
	Reason           string
	CreatedByUserID  uuid.NullUUID
	CreatedAt        time.Time
}

type ReceivablesReceivableAging struct {
	OrganizationID    uuid.UUID
	ReceivableID      uuid.UUID
	CustomerID        uuid.UUID
	CustomerLegalName string
	DocumentNumber    string
	CurrencyCode      interface{}
	OriginalAmount    interface{}
	BalanceAmount     interface{}
	IssuedOn          pgtype.Date
	DueOn             pgtype.Date
	DaysOverdue       interface{}
	AgingBucket       string
}
