// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreOrganization struct {
	ID       uuid.UUID
	Timezone string
	Status   string
}

type CoreOrganizationUser struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	Status         string
}

type CoreOrganizationUserRole struct {
	OrganizationID     uuid.UUID
	OrganizationUserID uuid.UUID
	RoleCode           string
}

type CoreUser struct {
	ID              uuid.UUID
	ExternalSubject string
	Status          string
}

type ReceivablesCollectionFollowup struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	ReceivableID      uuid.UUID
	FollowupType      string
	Notes             string
	PerformedAt       time.Time
	PerformedByUserID uuid.NullUUID
	NextActionOn      pgtype.Date
	CreatedAt         time.Time
}

type ReceivablesPayment struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	CustomerID        uuid.UUID
	ReceivedOn        pgtype.Date
	Amount            interface{}
	CurrencyCode      interface{}
	ExchangeRate      interface{}
	PaymentMethodCode string
	Reference         pgtype.Text
	Notes             pgtype.Text
	Status            string
	VoidReason        pgtype.Text
	VoidedAt          pgtype.Timestamptz
	ReceivedByUserID  uuid.NullUUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ReceivablesPaymentApplication struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	PaymentID        uuid.UUID
	ReceivableID     uuid.UUID
	Amount           interface{}
	AppliedAt        time.Time
	AppliedByUserID  uuid.NullUUID
	ReversedAt       pgtype.Timestamptz
	ReversedByUserID uuid.NullUUID
	ReversalReason   pgtype.Text
}

type ReceivablesPaymentPromise struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	ReceivableID    uuid.UUID
	FollowupID      uuid.NullUUID
	PromisedAmount  interface{}
	PromisedOn      pgtype.Date
	Status          string
	CreatedByUserID uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ReceivablesReceivable struct {
	ID                           uuid.UUID
	OrganizationID               uuid.UUID
	SourceInvoiceID              uuid.UUID
	SourceEventID                uuid.UUID
	CustomerID                   uuid.UUID
	CustomerIdentificationNumber string
	CustomerLegalName            string
	DocumentNumber               string
	CurrencyCode                 interface{}
	OriginalAmount               interface{}
	BalanceAmount                interface{}
	IssuedOn                     pgtype.Date
	DueOn                        pgtype.Date
	SaleConditionCode            string
	Status                       string
	SettledAt                    pgtype.Timestamptz
	CreatedAt                    time.Time
	UpdatedAt                    time.Time
}

type ReceivablesReceivableAdjustment struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	ReceivableID     uuid.UUID
	AdjustmentType   string
	SourceDocumentID uuid.NullUUID
	SourceEventID    uuid.NullUUID
	Amount           interface{}
	Reason           string
	CreatedByUserID  uuid.NullUUID
	CreatedAt        time.Time
}

type ReceivablesReceivableAging struct {
	OrganizationID    uuid.UUID
	ReceivableID      uuid.UUID
	CustomerID        uuid.UUID
	CustomerLegalName string
	DocumentNumber    string
	CurrencyCode      interface{}
	OriginalAmount    interface{}
	BalanceAmount     interface{}
	IssuedOn          pgtype.Date
	DueOn             pgtype.Date
	DaysOverdue       interface{}
	AgingBucket       string
}
