// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getOrganizationTimezone = `-- name: GetOrganizationTimezone :one

select timezone from core.organizations where id = $1
`

// Sesión con app.current_organization_id (política organizations_read).
func (q *Queries) GetOrganizationTimezone(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getOrganizationTimezone, id)
	var timezone string
	err := row.Scan(&timezone)
	return timezone, err
}
