// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getApplicationView = `-- name: GetApplicationView :one
select id, payment_id, receivable_id, trim_scale(amount)::text as amount, applied_at, reversed_at, reversal_reason
from receivables.payment_applications
where organization_id = $1 and id = $2
`

type GetApplicationViewParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetApplicationViewRow struct {
	ID             uuid.UUID
	PaymentID      uuid.UUID
	ReceivableID   uuid.UUID
	Amount         string
	AppliedAt      time.Time
	ReversedAt     pgtype.Timestamptz
	ReversalReason pgtype.Text
}

func (q *Queries) GetApplicationView(ctx context.Context, arg GetApplicationViewParams) (GetApplicationViewRow, error) {
	row := q.db.QueryRow(ctx, getApplicationView, arg.OrganizationID, arg.ID)
	var i GetApplicationViewRow
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.ReceivableID,
		&i.Amount,
		&i.AppliedAt,
		&i.ReversedAt,
		&i.ReversalReason,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one

select id, customer_id, received_on, trim_scale(amount)::text as amount, currency_code::text as currency_code,
       trim_scale(exchange_rate)::text as exchange_rate, payment_method_code, reference, notes, status, void_reason,
       voided_at, received_by_user_id, created_at
from receivables.payments
where organization_id = $1 and id = $2
`

type GetPaymentParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetPaymentRow struct {
	ID                uuid.UUID
	CustomerID        uuid.UUID
	ReceivedOn        pgtype.Date
	Amount            string
	CurrencyCode      string
	ExchangeRate      string
	PaymentMethodCode string
	Reference         pgtype.Text
	Notes             pgtype.Text
	Status            string
	VoidReason        pgtype.Text
	VoidedAt          pgtype.Timestamptz
	ReceivedByUserID  uuid.NullUUID
	CreatedAt         time.Time
}

// Lectura de pagos para la API. Filtro explícito por organización además de RLS.
func (q *Queries) GetPayment(ctx context.Context, arg GetPaymentParams) (GetPaymentRow, error) {
	row := q.db.QueryRow(ctx, getPayment, arg.OrganizationID, arg.ID)
	var i GetPaymentRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ReceivedOn,
		&i.Amount,
		&i.CurrencyCode,
		&i.ExchangeRate,
		&i.PaymentMethodCode,
		&i.Reference,
		&i.Notes,
		&i.Status,
		&i.VoidReason,
		&i.VoidedAt,
		&i.ReceivedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listApplicationsForPayments = `-- name: ListApplicationsForPayments :many
select id, payment_id, receivable_id, trim_scale(amount)::text as amount, applied_at, reversed_at, reversal_reason
from receivables.payment_applications
where organization_id = $1 and payment_id = any($2::text[]::uuid[])
order by applied_at, id
`

type ListApplicationsForPaymentsParams struct {
	OrganizationID uuid.UUID
	PaymentIds     []string
}

type ListApplicationsForPaymentsRow struct {
	ID             uuid.UUID
	PaymentID      uuid.UUID
	ReceivableID   uuid.UUID
	Amount         string
	AppliedAt      time.Time
	ReversedAt     pgtype.Timestamptz
	ReversalReason pgtype.Text
}

// Los ids viajan como text[]: con QueryExecModeExec (Supavisor) pgx no codifica un []uuid.UUID sin tipo.
func (q *Queries) ListApplicationsForPayments(ctx context.Context, arg ListApplicationsForPaymentsParams) ([]ListApplicationsForPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsForPayments, arg.OrganizationID, arg.PaymentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsForPaymentsRow{}
	for rows.Next() {
		var i ListApplicationsForPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.ReceivableID,
			&i.Amount,
			&i.AppliedAt,
			&i.ReversedAt,
			&i.ReversalReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many
select id, customer_id, received_on, trim_scale(amount)::text as amount, currency_code::text as currency_code,
       trim_scale(exchange_rate)::text as exchange_rate, payment_method_code, reference, notes, status, void_reason,
       voided_at, received_by_user_id, created_at
from receivables.payments
where organization_id = $1
  and ($2::uuid is null or customer_id = $2::uuid)
  and ($3::timestamptz is null
       or (created_at, id) < ($3::timestamptz, $4::uuid))
order by created_at desc, id desc
limit $5
`

type ListPaymentsParams struct {
	OrganizationID uuid.UUID
	CustomerID     uuid.NullUUID
	AfterCreatedAt pgtype.Timestamptz
	AfterID        uuid.NullUUID
	PageSize       int32
}

type ListPaymentsRow struct {
	ID                uuid.UUID
	CustomerID        uuid.UUID
	ReceivedOn        pgtype.Date
	Amount            string
	CurrencyCode      string
	ExchangeRate      string
	PaymentMethodCode string
	Reference         pgtype.Text
	Notes             pgtype.Text
	Status            string
	VoidReason        pgtype.Text
	VoidedAt          pgtype.Timestamptz
	ReceivedByUserID  uuid.NullUUID
	CreatedAt         time.Time
}

// Paginación por cursor sobre (created_at, id) descendente: índice payments_created_idx (00002).
func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]ListPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listPayments,
		arg.OrganizationID,
		arg.CustomerID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsRow{}
	for rows.Next() {
		var i ListPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ReceivedOn,
			&i.Amount,
			&i.CurrencyCode,
			&i.ExchangeRate,
			&i.PaymentMethodCode,
			&i.Reference,
			&i.Notes,
			&i.Status,
			&i.VoidReason,
			&i.VoidedAt,
			&i.ReceivedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
