// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receivables.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listReceivables = `-- name: ListReceivables :many

select id, source_invoice_id, customer_id, customer_legal_name, document_number,
       currency_code::text as currency_code,
       trim_scale(original_amount)::text as original_amount,
       trim_scale(balance_amount)::text as balance_amount,
       issued_on, due_on, status, settled_at, created_at
from receivables.receivables
where organization_id = $1
  and ($2::text is null or status = $2::text)
  and ($3::uuid is null or customer_id = $3::uuid)
  and ($4::boolean is null
       or (status in ('open', 'partially_paid') and due_on < $5::date) = $4::boolean)
  and ($6::timestamptz is null
       or (created_at, id) < ($6::timestamptz, $7::uuid))
order by created_at desc, id desc
limit $8
`

type ListReceivablesParams struct {
	OrganizationID uuid.UUID
	Status         pgtype.Text
	CustomerID     uuid.NullUUID
	Overdue        pgtype.Bool
	Today          pgtype.Date
	AfterCreatedAt pgtype.Timestamptz
	AfterID        uuid.NullUUID
	PageSize       int32
}

type ListReceivablesRow struct {
	ID                uuid.UUID
	SourceInvoiceID   uuid.UUID
	CustomerID        uuid.UUID
	CustomerLegalName string
	DocumentNumber    string
	CurrencyCode      string
	OriginalAmount    string
	BalanceAmount     string
	IssuedOn          pgtype.Date
	DueOn             pgtype.Date
	Status            string
	SettledAt         pgtype.Timestamptz
	CreatedAt         time.Time
}

// Sesión con app.current_organization_id (políticas *_tenant). El filtro por organización es explícito además
// de RLS: la consulta no depende solo de la política para quedar acotada al tenant.
// Paginación por cursor sobre (created_at, id) descendente: índices receivables_created_idx y
// receivables_status_created_idx (migración 00002). trim_scale quita los ceros de numeric(18,5): "1300.5", no
// "1300.50000" (mismo valor, el formato Money del contrato admite ambos).
// Vencida = todavía cobrable (open, partially_paid) y due_on anterior al día de negocio de la organización.
func (q *Queries) ListReceivables(ctx context.Context, arg ListReceivablesParams) ([]ListReceivablesRow, error) {
	rows, err := q.db.Query(ctx, listReceivables,
		arg.OrganizationID,
		arg.Status,
		arg.CustomerID,
		arg.Overdue,
		arg.Today,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReceivablesRow{}
	for rows.Next() {
		var i ListReceivablesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceInvoiceID,
			&i.CustomerID,
			&i.CustomerLegalName,
			&i.DocumentNumber,
			&i.CurrencyCode,
			&i.OriginalAmount,
			&i.BalanceAmount,
			&i.IssuedOn,
			&i.DueOn,
			&i.Status,
			&i.SettledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
