// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
insert into audit.audit_events (
  organization_id, service, actor_type, actor_user_id, action, entity_type, entity_id,
  correlation_id, ip_address, user_agent, payload
) values (
  $1, 'billing', $2, $3, $4,
  $5, $6, $7, $8::inet,
  $9, $10::text::jsonb
)
`

type InsertAuditEventParams struct {
	OrganizationID uuid.NullUUID
	ActorType      string
	ActorUserID    uuid.NullUUID
	Action         string
	EntityType     string
	EntityID       uuid.NullUUID
	CorrelationID  uuid.UUID
	IpAddress      *netip.Addr
	UserAgent      pgtype.Text
	Payload        string
}

// payload viaja como texto: con QueryExecModeExec pgx enviaría un []byte como bytea, no como JSON (ADR 0004).
// Sin RETURNING: la política de SELECT de audit_events exige organización y un evento global no la tiene.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.OrganizationID,
		arg.ActorType,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Payload,
	)
	return err
}
