// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getBranch = `-- name: GetBranch :one
select id, is_active from core.branches where organization_id = $1 and id = $2
`

type GetBranchParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetBranchRow struct {
	ID       uuid.UUID
	IsActive bool
}

// Un branch_id recibido se valida contra la organización activa (política branches_tenant).
func (q *Queries) GetBranch(ctx context.Context, arg GetBranchParams) (GetBranchRow, error) {
	row := q.db.QueryRow(ctx, getBranch, arg.OrganizationID, arg.ID)
	var i GetBranchRow
	err := row.Scan(&i.ID, &i.IsActive)
	return i, err
}

const getOrganizationSettings = `-- name: GetOrganizationSettings :one

select default_currency_code::text as default_currency_code, timezone
from core.organizations where id = $1 and status = 'active'
`

type GetOrganizationSettingsRow struct {
	DefaultCurrencyCode string
	Timezone            string
}

// Lecturas de otros schemas que Billing necesita para armar un documento. Solo SELECT (docs/decisiones/0002).
// La organización de la sesión (política organizations_read): moneda local y zona horaria de las fechas de negocio.
func (q *Queries) GetOrganizationSettings(ctx context.Context, organizationID uuid.UUID) (GetOrganizationSettingsRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationSettings, organizationID)
	var i GetOrganizationSettingsRow
	err := row.Scan(&i.DefaultCurrencyCode, &i.Timezone)
	return i, err
}

const listActiveTaxRates = `-- name: ListActiveTaxRates :many
select code, rate::text as rate from fiscal.tax_rates where is_active and code = any($1::text[])
`

type ListActiveTaxRatesRow struct {
	Code string
	Rate string
}

// Tarifas vigentes por código. El porcentaje sale del catálogo, nunca del cliente (informe 0001 §4.2).
func (q *Queries) ListActiveTaxRates(ctx context.Context, codes []string) ([]ListActiveTaxRatesRow, error) {
	rows, err := q.db.Query(ctx, listActiveTaxRates, codes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTaxRatesRow{}
	for rows.Next() {
		var i ListActiveTaxRatesRow
		if err := rows.Scan(&i.Code, &i.Rate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
