// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCustomer = `-- name: GetCustomer :one
select id, organization_id, identification_type_code, identification_number, legal_name,
       coalesce(trade_name, '')::text as trade_name, coalesce(email, '')::text as email,
       coalesce(phone, '')::text as phone, coalesce(address_details, '')::text as address,
       is_active, created_by_user_id, created_at, updated_at
from billing.customers where organization_id = $1 and id = $2
`

type GetCustomerParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetCustomerRow struct {
	ID                     uuid.UUID
	OrganizationID         uuid.UUID
	IdentificationTypeCode string
	IdentificationNumber   string
	LegalName              string
	TradeName              string
	Email                  string
	Phone                  string
	Address                string
	IsActive               bool
	CreatedByUserID        uuid.NullUUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) GetCustomer(ctx context.Context, arg GetCustomerParams) (GetCustomerRow, error) {
	row := q.db.QueryRow(ctx, getCustomer, arg.OrganizationID, arg.ID)
	var i GetCustomerRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.IdentificationTypeCode,
		&i.IdentificationNumber,
		&i.LegalName,
		&i.TradeName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerForUpdate = `-- name: GetCustomerForUpdate :one
select id, organization_id, identification_type_code, identification_number, legal_name,
       coalesce(trade_name, '')::text as trade_name, coalesce(email, '')::text as email,
       coalesce(phone, '')::text as phone, coalesce(address_details, '')::text as address,
       is_active, created_by_user_id, created_at, updated_at
from billing.customers where organization_id = $1 and id = $2
for update
`

type GetCustomerForUpdateParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetCustomerForUpdateRow struct {
	ID                     uuid.UUID
	OrganizationID         uuid.UUID
	IdentificationTypeCode string
	IdentificationNumber   string
	LegalName              string
	TradeName              string
	Email                  string
	Phone                  string
	Address                string
	IsActive               bool
	CreatedByUserID        uuid.NullUUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) GetCustomerForUpdate(ctx context.Context, arg GetCustomerForUpdateParams) (GetCustomerForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCustomerForUpdate, arg.OrganizationID, arg.ID)
	var i GetCustomerForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.IdentificationTypeCode,
		&i.IdentificationNumber,
		&i.LegalName,
		&i.TradeName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCustomer = `-- name: InsertCustomer :one

insert into billing.customers (organization_id, identification_type_code, identification_number, legal_name,
                               trade_name, email, phone, address_details, is_active, created_by_user_id)
values ($1, $2, $3,
        $4, nullif($5::text, ''), nullif($6::text, ''),
        nullif($7::text, ''), nullif($8::text, ''), true, $9)
returning id, organization_id, identification_type_code, identification_number, legal_name,
          coalesce(trade_name, '')::text as trade_name, coalesce(email, '')::text as email,
          coalesce(phone, '')::text as phone, coalesce(address_details, '')::text as address,
          is_active, created_by_user_id, created_at, updated_at
`

type InsertCustomerParams struct {
	OrganizationID         uuid.UUID
	IdentificationTypeCode string
	IdentificationNumber   string
	LegalName              string
	TradeName              string
	Email                  string
	Phone                  string
	Address                string
	CreatedByUserID        uuid.NullUUID
}

type InsertCustomerRow struct {
	ID                     uuid.UUID
	OrganizationID         uuid.UUID
	IdentificationTypeCode string
	IdentificationNumber   string
	LegalName              string
	TradeName              string
	Email                  string
	Phone                  string
	Address                string
	IsActive               bool
	CreatedByUserID        uuid.NullUUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

// Sesión con app.current_organization_id = organización activa (política customers_tenant). El filtro explícito por
// organization_id se mantiene además de RLS: defensa en profundidad y uso del índice.
// Todas las lecturas devuelven las mismas columnas, en el mismo orden (ver toCustomer).
func (q *Queries) InsertCustomer(ctx context.Context, arg InsertCustomerParams) (InsertCustomerRow, error) {
	row := q.db.QueryRow(ctx, insertCustomer,
		arg.OrganizationID,
		arg.IdentificationTypeCode,
		arg.IdentificationNumber,
		arg.LegalName,
		arg.TradeName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.CreatedByUserID,
	)
	var i InsertCustomerRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.IdentificationTypeCode,
		&i.IdentificationNumber,
		&i.LegalName,
		&i.TradeName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
select id, organization_id, identification_type_code, identification_number, legal_name,
       coalesce(trade_name, '')::text as trade_name, coalesce(email, '')::text as email,
       coalesce(phone, '')::text as phone, coalesce(address_details, '')::text as address,
       is_active, created_by_user_id, created_at, updated_at
from billing.customers
where organization_id = $1
  and ($2::boolean is null or is_active = $2::boolean)
  and ($3::text is null
       or legal_name ilike '%' || $3::text || '%' escape '\'
       or trade_name ilike '%' || $3::text || '%' escape '\'
       or identification_number ilike '%' || $3::text || '%' escape '\')
  and ($4::timestamptz is null
       or (created_at, id) > ($4::timestamptz, $5::uuid))
order by created_at, id
limit $6
`

type ListCustomersParams struct {
	OrganizationID uuid.UUID
	IsActive       pgtype.Bool
	Search         pgtype.Text
	AfterCreatedAt pgtype.Timestamptz
	AfterID        uuid.NullUUID
	PageSize       int32
}

type ListCustomersRow struct {
	ID                     uuid.UUID
	OrganizationID         uuid.UUID
	IdentificationTypeCode string
	IdentificationNumber   string
	LegalName              string
	TradeName              string
	Email                  string
	Phone                  string
	Address                string
	IsActive               bool
	CreatedByUserID        uuid.NullUUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.OrganizationID,
		arg.IsActive,
		arg.Search,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomersRow{}
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.IdentificationTypeCode,
			&i.IdentificationNumber,
			&i.LegalName,
			&i.TradeName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.IsActive,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
update billing.customers
set legal_name = $1, trade_name = nullif($2::text, ''),
    email = nullif($3::text, ''), phone = nullif($4::text, ''),
    address_details = nullif($5::text, ''), is_active = $6
where organization_id = $7 and id = $8
returning id, organization_id, identification_type_code, identification_number, legal_name,
          coalesce(trade_name, '')::text as trade_name, coalesce(email, '')::text as email,
          coalesce(phone, '')::text as phone, coalesce(address_details, '')::text as address,
          is_active, created_by_user_id, created_at, updated_at
`

type UpdateCustomerParams struct {
	LegalName      string
	TradeName      string
	Email          string
	Phone          string
	Address        string
	IsActive       bool
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type UpdateCustomerRow struct {
	ID                     uuid.UUID
	OrganizationID         uuid.UUID
	IdentificationTypeCode string
	IdentificationNumber   string
	LegalName              string
	TradeName              string
	Email                  string
	Phone                  string
	Address                string
	IsActive               bool
	CreatedByUserID        uuid.NullUUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (UpdateCustomerRow, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.LegalName,
		arg.TradeName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.IsActive,
		arg.OrganizationID,
		arg.ID,
	)
	var i UpdateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.IdentificationTypeCode,
		&i.IdentificationNumber,
		&i.LegalName,
		&i.TradeName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
