// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInvoiceDraft = `-- name: DeleteInvoiceDraft :execrows
delete from billing.invoices where organization_id = $1 and id = $2 and status = 'draft'
`

type DeleteInvoiceDraftParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) DeleteInvoiceDraft(ctx context.Context, arg DeleteInvoiceDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvoiceDraft, arg.OrganizationID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteInvoiceLines = `-- name: DeleteInvoiceLines :exec
delete from billing.invoice_lines where organization_id = $1 and invoice_id = $2
`

type DeleteInvoiceLinesParams struct {
	OrganizationID uuid.UUID
	InvoiceID      uuid.UUID
}

// Borra las líneas del borrador; sus impuestos caen por ON DELETE CASCADE. guard_draft_children lo impide si no es draft.
func (q *Queries) DeleteInvoiceLines(ctx context.Context, arg DeleteInvoiceLinesParams) error {
	_, err := q.db.Exec(ctx, deleteInvoiceLines, arg.OrganizationID, arg.InvoiceID)
	return err
}

const getInvoice = `-- name: GetInvoice :one
select id, organization_id, document_type, coalesce(number, '')::text as number, status, branch_id, customer_id,
       customer_identification_type_code, customer_identification_number, customer_legal_name, customer_email,
       customer_phone, customer_address, issued_at, coalesce(due_date::text, '')::text as due_date, sale_condition_code, credit_term_days,
       currency_code::text as currency_code, exchange_rate::text as exchange_rate,
       subtotal_amount::text as subtotal, discount_amount::text as discount, tax_amount::text as tax,
       exoneration_amount::text as exoneration, total_amount::text as total, coalesce(notes, '')::text as notes,
       referenced_invoice_id, coalesce(reference_reason, '')::text as reference_reason, requires_correction,
       coalesce(fiscal_rejection_reason, '')::text as fiscal_rejection_reason, created_by_user_id, issued_by_user_id,
       created_at, updated_at
from billing.invoices where organization_id = $1 and id = $2
`

type GetInvoiceParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetInvoiceRow struct {
	ID                             uuid.UUID
	OrganizationID                 uuid.UUID
	DocumentType                   string
	Number                         string
	Status                         string
	BranchID                       uuid.NullUUID
	CustomerID                     uuid.UUID
	CustomerIdentificationTypeCode pgtype.Text
	CustomerIdentificationNumber   pgtype.Text
	CustomerLegalName              pgtype.Text
	CustomerEmail                  pgtype.Text
	CustomerPhone                  pgtype.Text
	CustomerAddress                pgtype.Text
	IssuedAt                       pgtype.Timestamptz
	DueDate                        string
	SaleConditionCode              string
	CreditTermDays                 pgtype.Int4
	CurrencyCode                   string
	ExchangeRate                   string
	Subtotal                       string
	Discount                       string
	Tax                            string
	Exoneration                    string
	Total                          string
	Notes                          string
	ReferencedInvoiceID            uuid.NullUUID
	ReferenceReason                string
	RequiresCorrection             bool
	FiscalRejectionReason          string
	CreatedByUserID                uuid.UUID
	IssuedByUserID                 uuid.NullUUID
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
}

func (q *Queries) GetInvoice(ctx context.Context, arg GetInvoiceParams) (GetInvoiceRow, error) {
	row := q.db.QueryRow(ctx, getInvoice, arg.OrganizationID, arg.ID)
	var i GetInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentType,
		&i.Number,
		&i.Status,
		&i.BranchID,
		&i.CustomerID,
		&i.CustomerIdentificationTypeCode,
		&i.CustomerIdentificationNumber,
		&i.CustomerLegalName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.CustomerAddress,
		&i.IssuedAt,
		&i.DueDate,
		&i.SaleConditionCode,
		&i.CreditTermDays,
		&i.CurrencyCode,
		&i.ExchangeRate,
		&i.Subtotal,
		&i.Discount,
		&i.Tax,
		&i.Exoneration,
		&i.Total,
		&i.Notes,
		&i.ReferencedInvoiceID,
		&i.ReferenceReason,
		&i.RequiresCorrection,
		&i.FiscalRejectionReason,
		&i.CreatedByUserID,
		&i.IssuedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceForUpdate = `-- name: GetInvoiceForUpdate :one
select id, organization_id, document_type, coalesce(number, '')::text as number, status, branch_id, customer_id,
       customer_identification_type_code, customer_identification_number, customer_legal_name, customer_email,
       customer_phone, customer_address, issued_at, coalesce(due_date::text, '')::text as due_date, sale_condition_code, credit_term_days,
       currency_code::text as currency_code, exchange_rate::text as exchange_rate,
       subtotal_amount::text as subtotal, discount_amount::text as discount, tax_amount::text as tax,
       exoneration_amount::text as exoneration, total_amount::text as total, coalesce(notes, '')::text as notes,
       referenced_invoice_id, coalesce(reference_reason, '')::text as reference_reason, requires_correction,
       coalesce(fiscal_rejection_reason, '')::text as fiscal_rejection_reason, created_by_user_id, issued_by_user_id,
       created_at, updated_at
from billing.invoices where organization_id = $1 and id = $2
for update
`

type GetInvoiceForUpdateParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetInvoiceForUpdateRow struct {
	ID                             uuid.UUID
	OrganizationID                 uuid.UUID
	DocumentType                   string
	Number                         string
	Status                         string
	BranchID                       uuid.NullUUID
	CustomerID                     uuid.UUID
	CustomerIdentificationTypeCode pgtype.Text
	CustomerIdentificationNumber   pgtype.Text
	CustomerLegalName              pgtype.Text
	CustomerEmail                  pgtype.Text
	CustomerPhone                  pgtype.Text
	CustomerAddress                pgtype.Text
	IssuedAt                       pgtype.Timestamptz
	DueDate                        string
	SaleConditionCode              string
	CreditTermDays                 pgtype.Int4
	CurrencyCode                   string
	ExchangeRate                   string
	Subtotal                       string
	Discount                       string
	Tax                            string
	Exoneration                    string
	Total                          string
	Notes                          string
	ReferencedInvoiceID            uuid.NullUUID
	ReferenceReason                string
	RequiresCorrection             bool
	FiscalRejectionReason          string
	CreatedByUserID                uuid.UUID
	IssuedByUserID                 uuid.NullUUID
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
}

func (q *Queries) GetInvoiceForUpdate(ctx context.Context, arg GetInvoiceForUpdateParams) (GetInvoiceForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceForUpdate, arg.OrganizationID, arg.ID)
	var i GetInvoiceForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentType,
		&i.Number,
		&i.Status,
		&i.BranchID,
		&i.CustomerID,
		&i.CustomerIdentificationTypeCode,
		&i.CustomerIdentificationNumber,
		&i.CustomerLegalName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.CustomerAddress,
		&i.IssuedAt,
		&i.DueDate,
		&i.SaleConditionCode,
		&i.CreditTermDays,
		&i.CurrencyCode,
		&i.ExchangeRate,
		&i.Subtotal,
		&i.Discount,
		&i.Tax,
		&i.Exoneration,
		&i.Total,
		&i.Notes,
		&i.ReferencedInvoiceID,
		&i.ReferenceReason,
		&i.RequiresCorrection,
		&i.FiscalRejectionReason,
		&i.CreatedByUserID,
		&i.IssuedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertInvoice = `-- name: InsertInvoice :one

insert into billing.invoices (organization_id, document_type, status, branch_id, customer_id, sale_condition_code,
                              credit_term_days, currency_code, exchange_rate, notes, created_by_user_id,
                              subtotal_amount, discount_amount, tax_amount, exoneration_amount, total_amount)
values ($1, $2, 'draft', $3, $4,
        $5, $6, $7::text,
        $8::text::numeric, nullif($9::text, ''), $10,
        $11::text::numeric, $12::text::numeric, $13::text::numeric,
        $14::text::numeric, $15::text::numeric)
returning id, created_at, updated_at
`

type InsertInvoiceParams struct {
	OrganizationID    uuid.UUID
	DocumentType      string
	BranchID          uuid.NullUUID
	CustomerID        uuid.UUID
	SaleConditionCode string
	CreditTermDays    pgtype.Int4
	CurrencyCode      string
	ExchangeRate      string
	Notes             string
	CreatedByUserID   uuid.UUID
	Subtotal          string
	Discount          string
	Tax               string
	Exoneration       string
	Total             string
}

type InsertInvoiceRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Sesión con app.current_organization_id = organización activa (políticas *_tenant de billing). Los montos viajan
// como texto en ambos sentidos. La inmutabilidad de lo emitido la garantizan además invoices_guard y
// guard_draft_children.
func (q *Queries) InsertInvoice(ctx context.Context, arg InsertInvoiceParams) (InsertInvoiceRow, error) {
	row := q.db.QueryRow(ctx, insertInvoice,
		arg.OrganizationID,
		arg.DocumentType,
		arg.BranchID,
		arg.CustomerID,
		arg.SaleConditionCode,
		arg.CreditTermDays,
		arg.CurrencyCode,
		arg.ExchangeRate,
		arg.Notes,
		arg.CreatedByUserID,
		arg.Subtotal,
		arg.Discount,
		arg.Tax,
		arg.Exoneration,
		arg.Total,
	)
	var i InsertInvoiceRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const insertInvoiceLine = `-- name: InsertInvoiceLine :one
insert into billing.invoice_lines (organization_id, invoice_id, line_number, product_id, product_code, cabys_code,
                                   description, unit_of_measure_code, is_service, quantity, unit_price,
                                   discount_amount, discount_reason, subtotal_amount, tax_amount, total_amount)
values ($1, $2, $3, $4,
        nullif($5::text, ''), $6::text, $7,
        $8, $9, $10::text::numeric,
        $11::text::numeric, $12::text::numeric,
        nullif($13::text, ''), $14::text::numeric,
        $15::text::numeric, $16::text::numeric)
returning id
`

type InsertInvoiceLineParams struct {
	OrganizationID    uuid.UUID
	InvoiceID         uuid.UUID
	LineNumber        int32
	ProductID         uuid.NullUUID
	ProductCode       string
	CabysCode         string
	Description       string
	UnitOfMeasureCode string
	IsService         bool
	Quantity          string
	UnitPrice         string
	Discount          string
	DiscountReason    string
	Subtotal          string
	Tax               string
	Total             string
}

func (q *Queries) InsertInvoiceLine(ctx context.Context, arg InsertInvoiceLineParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertInvoiceLine,
		arg.OrganizationID,
		arg.InvoiceID,
		arg.LineNumber,
		arg.ProductID,
		arg.ProductCode,
		arg.CabysCode,
		arg.Description,
		arg.UnitOfMeasureCode,
		arg.IsService,
		arg.Quantity,
		arg.UnitPrice,
		arg.Discount,
		arg.DiscountReason,
		arg.Subtotal,
		arg.Tax,
		arg.Total,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertInvoiceLineTax = `-- name: InsertInvoiceLineTax :exec
insert into billing.invoice_line_taxes (organization_id, invoice_line_id, tax_type_code, tax_rate_code, rate,
                                        taxable_base, tax_amount)
values ($1, $2, $3,
        nullif($4::text, ''), $5::text::numeric,
        $6::text::numeric, $7::text::numeric)
`

type InsertInvoiceLineTaxParams struct {
	OrganizationID uuid.UUID
	InvoiceLineID  uuid.UUID
	TaxTypeCode    string
	TaxRateCode    string
	Rate           string
	TaxableBase    string
	TaxAmount      string
}

func (q *Queries) InsertInvoiceLineTax(ctx context.Context, arg InsertInvoiceLineTaxParams) error {
	_, err := q.db.Exec(ctx, insertInvoiceLineTax,
		arg.OrganizationID,
		arg.InvoiceLineID,
		arg.TaxTypeCode,
		arg.TaxRateCode,
		arg.Rate,
		arg.TaxableBase,
		arg.TaxAmount,
	)
	return err
}

const insertStatusChange = `-- name: InsertStatusChange :exec
insert into billing.invoice_status_history (organization_id, invoice_id, from_status, to_status, reason, changed_by_user_id, changed_at)
values ($1, $2, $3, $4,
        nullif($5::text, ''), $6, $7)
`

type InsertStatusChangeParams struct {
	OrganizationID  uuid.UUID
	InvoiceID       uuid.UUID
	FromStatus      pgtype.Text
	ToStatus        string
	Reason          string
	ChangedByUserID uuid.NullUUID
	ChangedAt       time.Time
}

func (q *Queries) InsertStatusChange(ctx context.Context, arg InsertStatusChangeParams) error {
	_, err := q.db.Exec(ctx, insertStatusChange,
		arg.OrganizationID,
		arg.InvoiceID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
		arg.ChangedByUserID,
		arg.ChangedAt,
	)
	return err
}

const issueInvoice = `-- name: IssueInvoice :one
update billing.invoices
set status = 'issued', number = $1::text, issued_at = $2::timestamptz,
    issued_by_user_id = $3::uuid, due_date = $4::text::date,
    customer_identification_type_code = $5::text,
    customer_identification_number = $6::text,
    customer_legal_name = $7::text, customer_email = nullif($8::text, ''),
    customer_phone = nullif($9::text, ''), customer_address = nullif($10::text, '')
where organization_id = $11 and id = $12 and status = 'draft'
returning updated_at
`

type IssueInvoiceParams struct {
	Number                         string
	IssuedAt                       time.Time
	IssuedByUserID                 uuid.UUID
	DueDate                        string
	CustomerIdentificationTypeCode string
	CustomerIdentificationNumber   string
	CustomerLegalName              string
	CustomerEmail                  string
	CustomerPhone                  string
	CustomerAddress                string
	OrganizationID                 uuid.UUID
	ID                             uuid.UUID
}

// draft → issued con los snapshots. El WHERE status = 'draft' y el trigger invoices_guard impiden emitir dos veces.
func (q *Queries) IssueInvoice(ctx context.Context, arg IssueInvoiceParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, issueInvoice,
		arg.Number,
		arg.IssuedAt,
		arg.IssuedByUserID,
		arg.DueDate,
		arg.CustomerIdentificationTypeCode,
		arg.CustomerIdentificationNumber,
		arg.CustomerLegalName,
		arg.CustomerEmail,
		arg.CustomerPhone,
		arg.CustomerAddress,
		arg.OrganizationID,
		arg.ID,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const listInvoiceLineTaxes = `-- name: ListInvoiceLineTaxes :many
select t.invoice_line_id, t.tax_type_code, coalesce(t.tax_rate_code, '')::text as tax_rate_code, t.rate::text as rate,
       t.taxable_base::text as taxable_base, t.tax_amount::text as tax_amount,
       t.exoneration_document_type_code, t.exoneration_document_number, t.exoneration_institution,
       t.exoneration_issued_at, coalesce(t.exoneration_percentage::text, '')::text as exoneration_rate,
       coalesce(t.exoneration_amount::text, '')::text as exoneration_amount
from billing.invoice_line_taxes t
join billing.invoice_lines l on l.organization_id = t.organization_id and l.id = t.invoice_line_id
where t.organization_id = $1 and l.invoice_id = any($2::text[]::uuid[])
order by t.invoice_line_id, t.tax_type_code
`

type ListInvoiceLineTaxesParams struct {
	OrganizationID uuid.UUID
	InvoiceIds     []string
}

type ListInvoiceLineTaxesRow struct {
	InvoiceLineID               uuid.UUID
	TaxTypeCode                 string
	TaxRateCode                 string
	Rate                        string
	TaxableBase                 string
	TaxAmount                   string
	ExonerationDocumentTypeCode pgtype.Text
	ExonerationDocumentNumber   pgtype.Text
	ExonerationInstitution      pgtype.Text
	ExonerationIssuedAt         pgtype.Timestamptz
	ExonerationRate             string
	ExonerationAmount           string
}

func (q *Queries) ListInvoiceLineTaxes(ctx context.Context, arg ListInvoiceLineTaxesParams) ([]ListInvoiceLineTaxesRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceLineTaxes, arg.OrganizationID, arg.InvoiceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceLineTaxesRow{}
	for rows.Next() {
		var i ListInvoiceLineTaxesRow
		if err := rows.Scan(
			&i.InvoiceLineID,
			&i.TaxTypeCode,
			&i.TaxRateCode,
			&i.Rate,
			&i.TaxableBase,
			&i.TaxAmount,
			&i.ExonerationDocumentTypeCode,
			&i.ExonerationDocumentNumber,
			&i.ExonerationInstitution,
			&i.ExonerationIssuedAt,
			&i.ExonerationRate,
			&i.ExonerationAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceLines = `-- name: ListInvoiceLines :many
select id, invoice_id, line_number, product_id, coalesce(product_code, '')::text as product_code,
       cabys_code::text as cabys_code, description, unit_of_measure_code, is_service, quantity::text as quantity,
       unit_price::text as unit_price, discount_amount::text as discount,
       coalesce(discount_reason, '')::text as discount_reason, subtotal_amount::text as subtotal,
       tax_amount::text as tax, total_amount::text as total
from billing.invoice_lines
where organization_id = $1 and invoice_id = any($2::text[]::uuid[])
order by invoice_id, line_number
`

type ListInvoiceLinesParams struct {
	OrganizationID uuid.UUID
	InvoiceIds     []string
}

type ListInvoiceLinesRow struct {
	ID                uuid.UUID
	InvoiceID         uuid.UUID
	LineNumber        int32
	ProductID         uuid.NullUUID
	ProductCode       string
	CabysCode         string
	Description       string
	UnitOfMeasureCode string
	IsService         bool
	Quantity          string
	UnitPrice         string
	Discount          string
	DiscountReason    string
	Subtotal          string
	Tax               string
	Total             string
}

// Líneas de varios documentos a la vez (ids como text[]: QueryExecModeExec).
func (q *Queries) ListInvoiceLines(ctx context.Context, arg ListInvoiceLinesParams) ([]ListInvoiceLinesRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceLines, arg.OrganizationID, arg.InvoiceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceLinesRow{}
	for rows.Next() {
		var i ListInvoiceLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.LineNumber,
			&i.ProductID,
			&i.ProductCode,
			&i.CabysCode,
			&i.Description,
			&i.UnitOfMeasureCode,
			&i.IsService,
			&i.Quantity,
			&i.UnitPrice,
			&i.Discount,
			&i.DiscountReason,
			&i.Subtotal,
			&i.Tax,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceStatusHistory = `-- name: ListInvoiceStatusHistory :many
select from_status, to_status, coalesce(reason, '')::text as reason, changed_by_user_id, changed_at
from billing.invoice_status_history
where organization_id = $1 and invoice_id = $2
order by changed_at, id
`

type ListInvoiceStatusHistoryParams struct {
	OrganizationID uuid.UUID
	InvoiceID      uuid.UUID
}

type ListInvoiceStatusHistoryRow struct {
	FromStatus      pgtype.Text
	ToStatus        string
	Reason          string
	ChangedByUserID uuid.NullUUID
	ChangedAt       time.Time
}

func (q *Queries) ListInvoiceStatusHistory(ctx context.Context, arg ListInvoiceStatusHistoryParams) ([]ListInvoiceStatusHistoryRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceStatusHistory, arg.OrganizationID, arg.InvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceStatusHistoryRow{}
	for rows.Next() {
		var i ListInvoiceStatusHistoryRow
		if err := rows.Scan(
			&i.FromStatus,
			&i.ToStatus,
			&i.Reason,
			&i.ChangedByUserID,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
select id, organization_id, document_type, coalesce(number, '')::text as number, status, branch_id, customer_id,
       customer_identification_type_code, customer_identification_number, customer_legal_name, customer_email,
       customer_phone, customer_address, issued_at, coalesce(due_date::text, '')::text as due_date, sale_condition_code, credit_term_days,
       currency_code::text as currency_code, exchange_rate::text as exchange_rate,
       subtotal_amount::text as subtotal, discount_amount::text as discount, tax_amount::text as tax,
       exoneration_amount::text as exoneration, total_amount::text as total, coalesce(notes, '')::text as notes,
       referenced_invoice_id, coalesce(reference_reason, '')::text as reference_reason, requires_correction,
       coalesce(fiscal_rejection_reason, '')::text as fiscal_rejection_reason, created_by_user_id, issued_by_user_id,
       created_at, updated_at
from billing.invoices
where organization_id = $1
  and ($2::text is null or document_type = $2::text)
  and ($3::text is null or status = $3::text)
  and ($4::uuid is null or customer_id = $4::uuid)
  and ($5::boolean is null or requires_correction = $5::boolean)
  and ($6::date is null
       or (issued_at at time zone $7::text)::date >= $6::date)
  and ($8::date is null
       or (issued_at at time zone $7::text)::date <= $8::date)
  and ($9::timestamptz is null
       or (created_at, id) > ($9::timestamptz, $10::uuid))
order by created_at, id
limit $11
`

type ListInvoicesParams struct {
	OrganizationID     uuid.UUID
	DocumentType       pgtype.Text
	Status             pgtype.Text
	CustomerID         uuid.NullUUID
	RequiresCorrection pgtype.Bool
	IssuedFrom         pgtype.Date
	Timezone           string
	IssuedTo           pgtype.Date
	AfterCreatedAt     pgtype.Timestamptz
	AfterID            uuid.NullUUID
	PageSize           int32
}

type ListInvoicesRow struct {
	ID                             uuid.UUID
	OrganizationID                 uuid.UUID
	DocumentType                   string
	Number                         string
	Status                         string
	BranchID                       uuid.NullUUID
	CustomerID                     uuid.UUID
	CustomerIdentificationTypeCode pgtype.Text
	CustomerIdentificationNumber   pgtype.Text
	CustomerLegalName              pgtype.Text
	CustomerEmail                  pgtype.Text
	CustomerPhone                  pgtype.Text
	CustomerAddress                pgtype.Text
	IssuedAt                       pgtype.Timestamptz
	DueDate                        string
	SaleConditionCode              string
	CreditTermDays                 pgtype.Int4
	CurrencyCode                   string
	ExchangeRate                   string
	Subtotal                       string
	Discount                       string
	Tax                            string
	Exoneration                    string
	Total                          string
	Notes                          string
	ReferencedInvoiceID            uuid.NullUUID
	ReferenceReason                string
	RequiresCorrection             bool
	FiscalRejectionReason          string
	CreatedByUserID                uuid.UUID
	IssuedByUserID                 uuid.NullUUID
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
}

// Orden estable por (created_at, id). Fechas de emisión en la zona de la organización (fecha de negocio).
func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]ListInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listInvoices,
		arg.OrganizationID,
		arg.DocumentType,
		arg.Status,
		arg.CustomerID,
		arg.RequiresCorrection,
		arg.IssuedFrom,
		arg.Timezone,
		arg.IssuedTo,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoicesRow{}
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentType,
			&i.Number,
			&i.Status,
			&i.BranchID,
			&i.CustomerID,
			&i.CustomerIdentificationTypeCode,
			&i.CustomerIdentificationNumber,
			&i.CustomerLegalName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.CustomerAddress,
			&i.IssuedAt,
			&i.DueDate,
			&i.SaleConditionCode,
			&i.CreditTermDays,
			&i.CurrencyCode,
			&i.ExchangeRate,
			&i.Subtotal,
			&i.Discount,
			&i.Tax,
			&i.Exoneration,
			&i.Total,
			&i.Notes,
			&i.ReferencedInvoiceID,
			&i.ReferenceReason,
			&i.RequiresCorrection,
			&i.FiscalRejectionReason,
			&i.CreatedByUserID,
			&i.IssuedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceDraft = `-- name: UpdateInvoiceDraft :one
update billing.invoices
set branch_id = $1, customer_id = $2,
    sale_condition_code = $3, credit_term_days = $4,
    currency_code = $5::text, exchange_rate = $6::text::numeric,
    notes = nullif($7::text, ''),
    subtotal_amount = $8::text::numeric, discount_amount = $9::text::numeric,
    tax_amount = $10::text::numeric, exoneration_amount = $11::text::numeric,
    total_amount = $12::text::numeric
where organization_id = $13 and id = $14 and status = 'draft'
returning updated_at
`

type UpdateInvoiceDraftParams struct {
	BranchID          uuid.NullUUID
	CustomerID        uuid.UUID
	SaleConditionCode string
	CreditTermDays    pgtype.Int4
	CurrencyCode      string
	ExchangeRate      string
	Notes             string
	Subtotal          string
	Discount          string
	Tax               string
	Exoneration       string
	Total             string
	OrganizationID    uuid.UUID
	ID                uuid.UUID
}

func (q *Queries) UpdateInvoiceDraft(ctx context.Context, arg UpdateInvoiceDraftParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, updateInvoiceDraft,
		arg.BranchID,
		arg.CustomerID,
		arg.SaleConditionCode,
		arg.CreditTermDays,
		arg.CurrencyCode,
		arg.ExchangeRate,
		arg.Notes,
		arg.Subtotal,
		arg.Discount,
		arg.Tax,
		arg.Exoneration,
		arg.Total,
		arg.OrganizationID,
		arg.ID,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}
