// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditAuditEvent struct {
	ID             uuid.UUID
	OrganizationID uuid.NullUUID
	OccurredAt     time.Time
	Service        string
	ActorType      string
	ActorUserID    uuid.NullUUID
	Action         string
	EntityType     string
	EntityID       uuid.NullUUID
	CorrelationID  uuid.UUID
	IpAddress      *netip.Addr
	UserAgent      pgtype.Text
	Payload        []byte
}

type BillingCustomer struct {
	ID                     uuid.UUID
	OrganizationID         uuid.UUID
	IdentificationTypeCode string
	IdentificationNumber   string
	LegalName              string
	TradeName              pgtype.Text
	Email                  pgtype.Text
	Phone                  pgtype.Text
	ProvinceCode           pgtype.Text
	CantonCode             pgtype.Text
	DistrictCode           pgtype.Text
	AddressDetails         pgtype.Text
	IsActive               bool
	CreatedByUserID        uuid.NullUUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type BillingDocumentSequence struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	DocumentType   string
	BranchID       uuid.NullUUID
	Prefix         string
	NextNumber     int64
	UpdatedAt      time.Time
	// Último número asignado al emitir; NULL = la secuencia nunca se usó y todavía se puede configurar.
	LastAssignedNumber pgtype.Int8
}

type BillingGooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

type BillingInvoice struct {
	ID                             uuid.UUID
	OrganizationID                 uuid.UUID
	DocumentType                   string
	Number                         pgtype.Text
	Status                         string
	BranchID                       uuid.NullUUID
	CustomerID                     uuid.UUID
	CustomerIdentificationTypeCode pgtype.Text
	CustomerIdentificationNumber   pgtype.Text
	CustomerLegalName              pgtype.Text
	CustomerEmail                  pgtype.Text
	CustomerPhone                  pgtype.Text
	CustomerAddress                pgtype.Text
	IssuedAt                       pgtype.Timestamptz
	DueDate                        pgtype.Date
	SaleConditionCode              string
	CreditTermDays                 pgtype.Int4
	CurrencyCode                   interface{}
	ExchangeRate                   interface{}
	SubtotalAmount                 interface{}
	DiscountAmount                 interface{}
	TaxAmount                      interface{}
	ExonerationAmount              interface{}
	TotalAmount                    interface{}
	Notes                          pgtype.Text
	ReferencedInvoiceID            uuid.NullUUID
	ReferenceReason                pgtype.Text
	RequiresCorrection             bool
	FiscalRejectionReason          pgtype.Text
	CancellationReason             pgtype.Text
	CancelledAt                    pgtype.Timestamptz
	CancelledByUserID              uuid.NullUUID
	CreatedByUserID                uuid.UUID
	IssuedByUserID                 uuid.NullUUID
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
}

type BillingInvoiceLine struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	InvoiceID         uuid.UUID
	LineNumber        int32
	ProductID         uuid.NullUUID
	ProductCode       pgtype.Text
	CabysCode         interface{}
	Description       string
	UnitOfMeasureCode string
	IsService         bool
	Quantity          interface{}
	UnitPrice         interface{}
	DiscountAmount    interface{}
	DiscountReason    pgtype.Text
	SubtotalAmount    interface{}
	TaxAmount         interface{}
	TotalAmount       interface{}
}

type BillingInvoiceLineTax struct {
	ID                          uuid.UUID
	OrganizationID              uuid.UUID
	InvoiceLineID               uuid.UUID
	TaxTypeCode                 string
	TaxRateCode                 pgtype.Text
	Rate                        interface{}
	TaxableBase                 interface{}
	TaxAmount                   interface{}
	ExonerationDocumentTypeCode pgtype.Text
	ExonerationDocumentNumber   pgtype.Text
	ExonerationInstitution      pgtype.Text
	ExonerationIssuedAt         pgtype.Timestamptz
	ExonerationPercentage       interface{}
	ExonerationAmount           interface{}
}

type BillingInvoicePaymentMethod struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	InvoiceID         uuid.UUID
	PaymentMethodCode string
	Amount            interface{}
}

type BillingInvoiceStatusHistory struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	InvoiceID       uuid.UUID
	FromStatus      pgtype.Text
	ToStatus        string
	Reason          pgtype.Text
	ChangedByUserID uuid.NullUUID
	ChangedAt       time.Time
}

type BillingProduct struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	Code              string
	Description       string
	CabysCode         interface{}
	UnitOfMeasureCode string
	UnitPrice         interface{}
	CurrencyCode      interface{}
	IsService         bool
	IsActive          bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type BillingProductTax struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	ProductID      uuid.UUID
	TaxTypeCode    string
	TaxRateCode    string
}

type CoreBranch struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Code           string
	Name           string
	IsActive       bool
}

type CoreOrganization struct {
	ID                  uuid.UUID
	Status              string
	Timezone            string
	DefaultCurrencyCode interface{}
}

type CoreOrganizationUser struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	Status         string
}

type CoreOrganizationUserRole struct {
	OrganizationID     uuid.UUID
	OrganizationUserID uuid.UUID
	RoleCode           string
}

type CoreUser struct {
	ID     uuid.UUID
	Status string
}

type FiscalTaxRate struct {
	Code     string
	Name     string
	Rate     interface{}
	IsActive bool
}

type IntegrationIdempotencyKey struct {
	Service        string
	OrganizationID uuid.UUID
	IdempotencyKey string
	RequestHash    interface{}
	ResponseStatus pgtype.Int4
	ResponseBody   []byte
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

type IntegrationOutboxMessage struct {
	ID              uuid.UUID
	SourceService   string
	OrganizationID  uuid.UUID
	EventType       string
	EventVersion    int32
	AggregateType   string
	AggregateID     uuid.UUID
	CorrelationID   uuid.UUID
	Payload         []byte
	OccurredAt      time.Time
	PublishedAt     pgtype.Timestamptz
	PublishAttempts int32
	NextAttemptAt   pgtype.Timestamptz
	LastError       pgtype.Text
}
