// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertOutboxMessage = `-- name: InsertOutboxMessage :exec
insert into integration.outbox_messages (id, source_service, organization_id, event_type, event_version, aggregate_type,
                                         aggregate_id, correlation_id, payload, occurred_at)
values ($1, $2, $3, $4, $5,
        $6, $7, $8, $9::text::jsonb,
        $10)
`

type InsertOutboxMessageParams struct {
	ID             uuid.UUID
	SourceService  string
	OrganizationID uuid.UUID
	EventType      string
	EventVersion   int32
	AggregateType  string
	AggregateID    uuid.UUID
	CorrelationID  uuid.UUID
	Payload        string
	OccurredAt     time.Time
}

// Evento en la misma transacción que la entidad (convenciones §10). Política outbox_messages_service:
// source_service = shared.current_service() = 'billing'. El payload viaja como texto (jsonb con QueryExecModeExec).
// Sin RETURNING: la API solo escribe; publicar es trabajo del worker (P2).
func (q *Queries) InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error {
	_, err := q.db.Exec(ctx, insertOutboxMessage,
		arg.ID,
		arg.SourceService,
		arg.OrganizationID,
		arg.EventType,
		arg.EventVersion,
		arg.AggregateType,
		arg.AggregateID,
		arg.CorrelationID,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}
