// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProductTaxes = `-- name: DeleteProductTaxes :exec
delete from billing.product_taxes where organization_id = $1 and product_id = $2
`

type DeleteProductTaxesParams struct {
	OrganizationID uuid.UUID
	ProductID      uuid.UUID
}

func (q *Queries) DeleteProductTaxes(ctx context.Context, arg DeleteProductTaxesParams) error {
	_, err := q.db.Exec(ctx, deleteProductTaxes, arg.OrganizationID, arg.ProductID)
	return err
}

const getProduct = `-- name: GetProduct :one
select id, organization_id, code, description, cabys_code::text as cabys_code, unit_of_measure_code,
       unit_price::text as unit_price, currency_code::text as currency_code, is_service, is_active,
       created_at, updated_at
from billing.products where organization_id = $1 and id = $2
`

type GetProductParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetProductRow struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	Code              string
	Description       string
	CabysCode         string
	UnitOfMeasureCode string
	UnitPrice         string
	CurrencyCode      string
	IsService         bool
	IsActive          bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, arg.OrganizationID, arg.ID)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Description,
		&i.CabysCode,
		&i.UnitOfMeasureCode,
		&i.UnitPrice,
		&i.CurrencyCode,
		&i.IsService,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductForUpdate = `-- name: GetProductForUpdate :one
select id, organization_id, code, description, cabys_code::text as cabys_code, unit_of_measure_code,
       unit_price::text as unit_price, currency_code::text as currency_code, is_service, is_active,
       created_at, updated_at
from billing.products where organization_id = $1 and id = $2
for update
`

type GetProductForUpdateParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetProductForUpdateRow struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	Code              string
	Description       string
	CabysCode         string
	UnitOfMeasureCode string
	UnitPrice         string
	CurrencyCode      string
	IsService         bool
	IsActive          bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) GetProductForUpdate(ctx context.Context, arg GetProductForUpdateParams) (GetProductForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getProductForUpdate, arg.OrganizationID, arg.ID)
	var i GetProductForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Description,
		&i.CabysCode,
		&i.UnitOfMeasureCode,
		&i.UnitPrice,
		&i.CurrencyCode,
		&i.IsService,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one

insert into billing.products (organization_id, code, description, cabys_code, unit_of_measure_code, unit_price,
                              currency_code, is_service, is_active)
values ($1, $2, $3, $4::text,
        $5, $6::text::numeric, $7::text,
        $8, $9)
returning id, organization_id, code, description, cabys_code::text as cabys_code, unit_of_measure_code,
          unit_price::text as unit_price, currency_code::text as currency_code, is_service, is_active,
          created_at, updated_at
`

type InsertProductParams struct {
	OrganizationID    uuid.UUID
	Code              string
	Description       string
	CabysCode         string
	UnitOfMeasureCode string
	UnitPrice         string
	CurrencyCode      string
	IsService         bool
	IsActive          bool
}

type InsertProductRow struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	Code              string
	Description       string
	CabysCode         string
	UnitOfMeasureCode string
	UnitPrice         string
	CurrencyCode      string
	IsService         bool
	IsActive          bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// Sesión con app.current_organization_id = organización activa (políticas products_tenant y product_taxes_tenant).
// Los montos viajan como texto en ambos sentidos: nunca pasan por float ni por un tipo numérico del driver.
func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (InsertProductRow, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.OrganizationID,
		arg.Code,
		arg.Description,
		arg.CabysCode,
		arg.UnitOfMeasureCode,
		arg.UnitPrice,
		arg.CurrencyCode,
		arg.IsService,
		arg.IsActive,
	)
	var i InsertProductRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Description,
		&i.CabysCode,
		&i.UnitOfMeasureCode,
		&i.UnitPrice,
		&i.CurrencyCode,
		&i.IsService,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProductTax = `-- name: InsertProductTax :exec
insert into billing.product_taxes (organization_id, product_id, tax_type_code, tax_rate_code)
values ($1, $2, $3, $4)
`

type InsertProductTaxParams struct {
	OrganizationID uuid.UUID
	ProductID      uuid.UUID
	TaxTypeCode    string
	TaxRateCode    string
}

func (q *Queries) InsertProductTax(ctx context.Context, arg InsertProductTaxParams) error {
	_, err := q.db.Exec(ctx, insertProductTax,
		arg.OrganizationID,
		arg.ProductID,
		arg.TaxTypeCode,
		arg.TaxRateCode,
	)
	return err
}

const listProductTaxes = `-- name: ListProductTaxes :many
select product_id, tax_type_code, tax_rate_code
from billing.product_taxes
where organization_id = $1 and product_id = any($2::text[]::uuid[])
order by product_id, tax_type_code
`

type ListProductTaxesParams struct {
	OrganizationID uuid.UUID
	ProductIds     []string
}

type ListProductTaxesRow struct {
	ProductID   uuid.UUID
	TaxTypeCode string
	TaxRateCode string
}

// Impuestos de varios productos a la vez: una consulta por página, no una por producto.
// Los ids viajan como text[]: con QueryExecModeExec (Supavisor) pgx no sabe codificar un []uuid.UUID sin describir
// el statement, igual que un jsonb viaja como texto (ADR 0004 de Platform).
func (q *Queries) ListProductTaxes(ctx context.Context, arg ListProductTaxesParams) ([]ListProductTaxesRow, error) {
	rows, err := q.db.Query(ctx, listProductTaxes, arg.OrganizationID, arg.ProductIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductTaxesRow{}
	for rows.Next() {
		var i ListProductTaxesRow
		if err := rows.Scan(&i.ProductID, &i.TaxTypeCode, &i.TaxRateCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
select id, organization_id, code, description, cabys_code::text as cabys_code, unit_of_measure_code,
       unit_price::text as unit_price, currency_code::text as currency_code, is_service, is_active,
       created_at, updated_at
from billing.products
where organization_id = $1
  and ($2::boolean is null or is_active = $2::boolean)
  and ($3::text is null
       or code ilike '%' || $3::text || '%' escape '\'
       or description ilike '%' || $3::text || '%' escape '\')
  and ($4::timestamptz is null
       or (created_at, id) > ($4::timestamptz, $5::uuid))
order by created_at, id
limit $6
`

type ListProductsParams struct {
	OrganizationID uuid.UUID
	IsActive       pgtype.Bool
	Search         pgtype.Text
	AfterCreatedAt pgtype.Timestamptz
	AfterID        uuid.NullUUID
	PageSize       int32
}

type ListProductsRow struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	Code              string
	Description       string
	CabysCode         string
	UnitOfMeasureCode string
	UnitPrice         string
	CurrencyCode      string
	IsService         bool
	IsActive          bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.OrganizationID,
		arg.IsActive,
		arg.Search,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Code,
			&i.Description,
			&i.CabysCode,
			&i.UnitOfMeasureCode,
			&i.UnitPrice,
			&i.CurrencyCode,
			&i.IsService,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
update billing.products
set code = $1, description = $2, cabys_code = $3::text,
    unit_of_measure_code = $4, unit_price = $5::text::numeric,
    currency_code = $6::text, is_service = $7, is_active = $8
where organization_id = $9 and id = $10
returning id, organization_id, code, description, cabys_code::text as cabys_code, unit_of_measure_code,
          unit_price::text as unit_price, currency_code::text as currency_code, is_service, is_active,
          created_at, updated_at
`

type UpdateProductParams struct {
	Code              string
	Description       string
	CabysCode         string
	UnitOfMeasureCode string
	UnitPrice         string
	CurrencyCode      string
	IsService         bool
	IsActive          bool
	OrganizationID    uuid.UUID
	ID                uuid.UUID
}

type UpdateProductRow struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	Code              string
	Description       string
	CabysCode         string
	UnitOfMeasureCode string
	UnitPrice         string
	CurrencyCode      string
	IsService         bool
	IsActive          bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Code,
		arg.Description,
		arg.CabysCode,
		arg.UnitOfMeasureCode,
		arg.UnitPrice,
		arg.CurrencyCode,
		arg.IsService,
		arg.IsActive,
		arg.OrganizationID,
		arg.ID,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Description,
		&i.CabysCode,
		&i.UnitOfMeasureCode,
		&i.UnitPrice,
		&i.CurrencyCode,
		&i.IsService,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
