// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sequences.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSequenceForUpdate = `-- name: GetSequenceForUpdate :one
select id, organization_id, document_type, branch_id, prefix, next_number, last_assigned_number, updated_at
from billing.document_sequences
where organization_id = $1 and document_type = $2
  and branch_id is not distinct from $3::uuid
for update
`

type GetSequenceForUpdateParams struct {
	OrganizationID uuid.UUID
	DocumentType   string
	BranchID       uuid.NullUUID
}

type GetSequenceForUpdateRow struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	DocumentType       string
	BranchID           uuid.NullUUID
	Prefix             string
	NextNumber         int64
	LastAssignedNumber pgtype.Int8
	UpdatedAt          time.Time
}

func (q *Queries) GetSequenceForUpdate(ctx context.Context, arg GetSequenceForUpdateParams) (GetSequenceForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getSequenceForUpdate, arg.OrganizationID, arg.DocumentType, arg.BranchID)
	var i GetSequenceForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentType,
		&i.BranchID,
		&i.Prefix,
		&i.NextNumber,
		&i.LastAssignedNumber,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSequence = `-- name: InsertSequence :one
insert into billing.document_sequences (organization_id, document_type, branch_id, prefix, next_number)
values ($1, $2, $3, $4, $5)
returning id, organization_id, document_type, branch_id, prefix, next_number, last_assigned_number, updated_at
`

type InsertSequenceParams struct {
	OrganizationID uuid.UUID
	DocumentType   string
	BranchID       uuid.NullUUID
	Prefix         string
	NextNumber     int64
}

type InsertSequenceRow struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	DocumentType       string
	BranchID           uuid.NullUUID
	Prefix             string
	NextNumber         int64
	LastAssignedNumber pgtype.Int8
	UpdatedAt          time.Time
}

func (q *Queries) InsertSequence(ctx context.Context, arg InsertSequenceParams) (InsertSequenceRow, error) {
	row := q.db.QueryRow(ctx, insertSequence,
		arg.OrganizationID,
		arg.DocumentType,
		arg.BranchID,
		arg.Prefix,
		arg.NextNumber,
	)
	var i InsertSequenceRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentType,
		&i.BranchID,
		&i.Prefix,
		&i.NextNumber,
		&i.LastAssignedNumber,
		&i.UpdatedAt,
	)
	return i, err
}

const listSequences = `-- name: ListSequences :many

select id, organization_id, document_type, branch_id, prefix, next_number, last_assigned_number, updated_at
from billing.document_sequences
where organization_id = $1
order by document_type, branch_id nulls first
`

type ListSequencesRow struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	DocumentType       string
	BranchID           uuid.NullUUID
	Prefix             string
	NextNumber         int64
	LastAssignedNumber pgtype.Int8
	UpdatedAt          time.Time
}

// Sesión con app.current_organization_id = organización activa (política document_sequences_tenant).
func (q *Queries) ListSequences(ctx context.Context, organizationID uuid.UUID) ([]ListSequencesRow, error) {
	rows, err := q.db.Query(ctx, listSequences, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSequencesRow{}
	for rows.Next() {
		var i ListSequencesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentType,
			&i.BranchID,
			&i.Prefix,
			&i.NextNumber,
			&i.LastAssignedNumber,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSequences = `-- name: LockSequences :exec
select pg_advisory_xact_lock(hashtextextended('billing.document_sequences:' || $1::text
                                              || ':' || $2::text, 0))
`

type LockSequencesParams struct {
	OrganizationID string
	DocumentType   string
}

// Serializa las operaciones sobre las secuencias de un tipo de documento en la organización: configurar (el prefijo
// no se repite) y asignar números. Es de transacción: se libera al confirmar o revertir.
func (q *Queries) LockSequences(ctx context.Context, arg LockSequencesParams) error {
	_, err := q.db.Exec(ctx, lockSequences, arg.OrganizationID, arg.DocumentType)
	return err
}

const updateSequence = `-- name: UpdateSequence :one
update billing.document_sequences
set prefix = $1, next_number = $2, last_assigned_number = $3
where organization_id = $4 and id = $5
returning id, organization_id, document_type, branch_id, prefix, next_number, last_assigned_number, updated_at
`

type UpdateSequenceParams struct {
	Prefix             string
	NextNumber         int64
	LastAssignedNumber pgtype.Int8
	OrganizationID     uuid.UUID
	ID                 uuid.UUID
}

type UpdateSequenceRow struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	DocumentType       string
	BranchID           uuid.NullUUID
	Prefix             string
	NextNumber         int64
	LastAssignedNumber pgtype.Int8
	UpdatedAt          time.Time
}

func (q *Queries) UpdateSequence(ctx context.Context, arg UpdateSequenceParams) (UpdateSequenceRow, error) {
	row := q.db.QueryRow(ctx, updateSequence,
		arg.Prefix,
		arg.NextNumber,
		arg.LastAssignedNumber,
		arg.OrganizationID,
		arg.ID,
	)
	var i UpdateSequenceRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentType,
		&i.BranchID,
		&i.Prefix,
		&i.NextNumber,
		&i.LastAssignedNumber,
		&i.UpdatedAt,
	)
	return i, err
}
