// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branches.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBranch = `-- name: GetBranch :one
select id, organization_id, code, name, coalesce(address, '')::text as address, coalesce(phone, '')::text as phone,
       coalesce(email, '')::text as email, is_active, created_at, updated_at
from core.branches where organization_id = $1 and id = $2
`

type GetBranchParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetBranchRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Code           string
	Name           string
	Address        string
	Phone          string
	Email          string
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetBranch(ctx context.Context, arg GetBranchParams) (GetBranchRow, error) {
	row := q.db.QueryRow(ctx, getBranch, arg.OrganizationID, arg.ID)
	var i GetBranchRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBranchForUpdate = `-- name: GetBranchForUpdate :one
select id, organization_id, code, name, coalesce(address, '')::text as address, coalesce(phone, '')::text as phone,
       coalesce(email, '')::text as email, is_active, created_at, updated_at
from core.branches where organization_id = $1 and id = $2
for update
`

type GetBranchForUpdateParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetBranchForUpdateRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Code           string
	Name           string
	Address        string
	Phone          string
	Email          string
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetBranchForUpdate(ctx context.Context, arg GetBranchForUpdateParams) (GetBranchForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getBranchForUpdate, arg.OrganizationID, arg.ID)
	var i GetBranchForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBranch = `-- name: InsertBranch :one

insert into core.branches (organization_id, code, name, address, phone, email)
values ($1, $2, $3, nullif($4::text, ''),
        nullif($5::text, ''), nullif($6::text, ''))
returning id, organization_id, code, name, coalesce(address, '')::text as address, coalesce(phone, '')::text as phone,
          coalesce(email, '')::text as email, is_active, created_at, updated_at
`

type InsertBranchParams struct {
	OrganizationID uuid.UUID
	Code           string
	Name           string
	Address        string
	Phone          string
	Email          string
}

type InsertBranchRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Code           string
	Name           string
	Address        string
	Phone          string
	Email          string
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Sesión con app.current_organization_id = organización activa (política branches_tenant).
func (q *Queries) InsertBranch(ctx context.Context, arg InsertBranchParams) (InsertBranchRow, error) {
	row := q.db.QueryRow(ctx, insertBranch,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Email,
	)
	var i InsertBranchRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBranches = `-- name: ListBranches :many
select id, organization_id, code, name, coalesce(address, '')::text as address, coalesce(phone, '')::text as phone,
       coalesce(email, '')::text as email, is_active, created_at, updated_at
from core.branches
where organization_id = $1
  and ($2::boolean is null or is_active = $2::boolean)
  and ($3::timestamptz is null
       or (created_at, id) > ($3::timestamptz, $4::uuid))
order by created_at, id
limit $5
`

type ListBranchesParams struct {
	OrganizationID uuid.UUID
	IsActive       pgtype.Bool
	AfterCreatedAt pgtype.Timestamptz
	AfterID        uuid.NullUUID
	PageSize       int32
}

type ListBranchesRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Code           string
	Name           string
	Address        string
	Phone          string
	Email          string
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListBranches(ctx context.Context, arg ListBranchesParams) ([]ListBranchesRow, error) {
	rows, err := q.db.Query(ctx, listBranches,
		arg.OrganizationID,
		arg.IsActive,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBranchesRow{}
	for rows.Next() {
		var i ListBranchesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Code,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranch = `-- name: UpdateBranch :one
update core.branches
set name = $1, address = nullif($2::text, ''), phone = nullif($3::text, ''),
    email = nullif($4::text, ''), is_active = $5
where organization_id = $6 and id = $7
returning id, organization_id, code, name, coalesce(address, '')::text as address, coalesce(phone, '')::text as phone,
          coalesce(email, '')::text as email, is_active, created_at, updated_at
`

type UpdateBranchParams struct {
	Name           string
	Address        string
	Phone          string
	Email          string
	IsActive       bool
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type UpdateBranchRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Code           string
	Name           string
	Address        string
	Phone          string
	Email          string
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (UpdateBranchRow, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.IsActive,
		arg.OrganizationID,
		arg.ID,
	)
	var i UpdateBranchRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
