// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one
insert into integration.idempotency_keys (service, organization_id, idempotency_key, request_hash, expires_at)
values ('platform', $1, $2, $3::text, now() + make_interval(secs => $4::bigint))
on conflict (service, organization_id, idempotency_key) do nothing
returning request_hash::text
`

type ClaimIdempotencyKeyParams struct {
	OrganizationID uuid.UUID
	IdempotencyKey string
	RequestHash    string
	TtlSeconds     int64
}

// Si otra transacción ya reservó la clave, este insert espera a que confirme y luego no devuelve fila.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.OrganizationID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.TtlSeconds,
	)
	var request_hash string
	err := row.Scan(&request_hash)
	return request_hash, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
update integration.idempotency_keys
set response_status = $1, response_body = $2::text::jsonb
where service = 'platform' and organization_id = $3 and idempotency_key = $4
`

type CompleteIdempotencyKeyParams struct {
	ResponseStatus pgtype.Int4
	ResponseBody   string
	OrganizationID uuid.UUID
	IdempotencyKey string
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.OrganizationID,
		arg.IdempotencyKey,
	)
	return err
}

const deleteExpiredIdempotencyKey = `-- name: DeleteExpiredIdempotencyKey :exec

delete from integration.idempotency_keys
where service = 'platform' and organization_id = $1 and idempotency_key = $2 and expires_at < now()
`

type DeleteExpiredIdempotencyKeyParams struct {
	OrganizationID uuid.UUID
	IdempotencyKey string
}

// Sesión con app.current_organization_id = organización del comando (política idempotency_keys_service).
func (q *Queries) DeleteExpiredIdempotencyKey(ctx context.Context, arg DeleteExpiredIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKey, arg.OrganizationID, arg.IdempotencyKey)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
select request_hash::text as request_hash, response_status, response_body
from integration.idempotency_keys
where service = 'platform' and organization_id = $1 and idempotency_key = $2
`

type GetIdempotencyKeyParams struct {
	OrganizationID uuid.UUID
	IdempotencyKey string
}

type GetIdempotencyKeyRow struct {
	RequestHash    string
	ResponseStatus pgtype.Int4
	ResponseBody   []byte
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.OrganizationID, arg.IdempotencyKey)
	var i GetIdempotencyKeyRow
	err := row.Scan(&i.RequestHash, &i.ResponseStatus, &i.ResponseBody)
	return i, err
}
