// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
update core.invitations set status = 'accepted', accepted_at = now(), accepted_by_user_id = $1
where organization_id = $2 and id = $3 and status = 'pending'
`

type AcceptInvitationParams struct {
	UserID         uuid.NullUUID
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) error {
	_, err := q.db.Exec(ctx, acceptInvitation, arg.UserID, arg.OrganizationID, arg.ID)
	return err
}

const expirePendingInvitationForEmail = `-- name: ExpirePendingInvitationForEmail :exec
update core.invitations set status = 'expired'
where organization_id = $1 and lower(email) = lower($2::text) and status = 'pending' and expires_at <= now()
`

type ExpirePendingInvitationForEmailParams struct {
	OrganizationID uuid.UUID
	Email          string
}

// Las pendientes vencidas se marcan al volver a invitar al mismo email (libera invitations_pending_email_uk).
func (q *Queries) ExpirePendingInvitationForEmail(ctx context.Context, arg ExpirePendingInvitationForEmailParams) error {
	_, err := q.db.Exec(ctx, expirePendingInvitationForEmail, arg.OrganizationID, arg.Email)
	return err
}

const findInvitationByTokenHash = `-- name: FindInvitationByTokenHash :one
select id, organization_id, email, role_code, status, expires_at, invited_by_user_id, accepted_by_user_id, accepted_at, created_at
from core.invitations
where token_hash = $1::text
`

type FindInvitationByTokenHashRow struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	Email            string
	RoleCode         string
	Status           string
	ExpiresAt        time.Time
	InvitedByUserID  uuid.UUID
	AcceptedByUserID uuid.NullUUID
	AcceptedAt       pgtype.Timestamptz
	CreatedAt        time.Time
}

// Sesión del invitado (app.current_user_id): la política invitations_invitee solo deja ver las invitaciones
// dirigidas a su email. Un token válido de otra persona no devuelve nada.
func (q *Queries) FindInvitationByTokenHash(ctx context.Context, tokenHash string) (FindInvitationByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findInvitationByTokenHash, tokenHash)
	var i FindInvitationByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleCode,
		&i.Status,
		&i.ExpiresAt,
		&i.InvitedByUserID,
		&i.AcceptedByUserID,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByTokenHashForUpdate = `-- name: GetInvitationByTokenHashForUpdate :one
select id, organization_id, email, role_code, status, expires_at, invited_by_user_id, accepted_by_user_id, accepted_at, created_at
from core.invitations
where organization_id = $1 and token_hash = $2::text
for update
`

type GetInvitationByTokenHashForUpdateParams struct {
	OrganizationID uuid.UUID
	TokenHash      string
}

type GetInvitationByTokenHashForUpdateRow struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	Email            string
	RoleCode         string
	Status           string
	ExpiresAt        time.Time
	InvitedByUserID  uuid.UUID
	AcceptedByUserID uuid.NullUUID
	AcceptedAt       pgtype.Timestamptz
	CreatedAt        time.Time
}

func (q *Queries) GetInvitationByTokenHashForUpdate(ctx context.Context, arg GetInvitationByTokenHashForUpdateParams) (GetInvitationByTokenHashForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHashForUpdate, arg.OrganizationID, arg.TokenHash)
	var i GetInvitationByTokenHashForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleCode,
		&i.Status,
		&i.ExpiresAt,
		&i.InvitedByUserID,
		&i.AcceptedByUserID,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationForUpdate = `-- name: GetInvitationForUpdate :one
select id, organization_id, email, role_code, status, expires_at, invited_by_user_id, accepted_by_user_id, accepted_at, created_at
from core.invitations
where organization_id = $1 and id = $2
for update
`

type GetInvitationForUpdateParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

type GetInvitationForUpdateRow struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	Email            string
	RoleCode         string
	Status           string
	ExpiresAt        time.Time
	InvitedByUserID  uuid.UUID
	AcceptedByUserID uuid.NullUUID
	AcceptedAt       pgtype.Timestamptz
	CreatedAt        time.Time
}

func (q *Queries) GetInvitationForUpdate(ctx context.Context, arg GetInvitationForUpdateParams) (GetInvitationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getInvitationForUpdate, arg.OrganizationID, arg.ID)
	var i GetInvitationForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleCode,
		&i.Status,
		&i.ExpiresAt,
		&i.InvitedByUserID,
		&i.AcceptedByUserID,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertInvitation = `-- name: InsertInvitation :one

insert into core.invitations (organization_id, email, role_code, token_hash, expires_at, invited_by_user_id)
values ($1, $2, $3, $4::text,
        $5, $6)
returning id, created_at
`

type InsertInvitationParams struct {
	OrganizationID  uuid.UUID
	Email           string
	RoleCode        string
	TokenHash       string
	ExpiresAt       time.Time
	InvitedByUserID uuid.UUID
}

type InsertInvitationRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

// Salvo FindInvitationByTokenHash, todas corren en la organización de la invitación (política invitations_tenant).
func (q *Queries) InsertInvitation(ctx context.Context, arg InsertInvitationParams) (InsertInvitationRow, error) {
	row := q.db.QueryRow(ctx, insertInvitation,
		arg.OrganizationID,
		arg.Email,
		arg.RoleCode,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.InvitedByUserID,
	)
	var i InsertInvitationRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const isActiveMemberEmail = `-- name: IsActiveMemberEmail :one
select exists (
  select 1 from core.organization_users ou join core.users u on u.id = ou.user_id
  where ou.organization_id = $1 and lower(u.email) = lower($2::text) and ou.status = 'active'
)
`

type IsActiveMemberEmailParams struct {
	OrganizationID uuid.UUID
	Email          string
}

func (q *Queries) IsActiveMemberEmail(ctx context.Context, arg IsActiveMemberEmailParams) (bool, error) {
	row := q.db.QueryRow(ctx, isActiveMemberEmail, arg.OrganizationID, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listInvitations = `-- name: ListInvitations :many
select id, organization_id, email, role_code, status, expires_at, invited_by_user_id, accepted_by_user_id, accepted_at, created_at
from core.invitations
where organization_id = $1
  and ($2::text is null or status = $2::text)
  and ($3::timestamptz is null
       or (created_at, id) > ($3::timestamptz, $4::uuid))
order by created_at, id
limit $5
`

type ListInvitationsParams struct {
	OrganizationID uuid.UUID
	Status         pgtype.Text
	AfterCreatedAt pgtype.Timestamptz
	AfterID        uuid.NullUUID
	PageSize       int32
}

type ListInvitationsRow struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	Email            string
	RoleCode         string
	Status           string
	ExpiresAt        time.Time
	InvitedByUserID  uuid.UUID
	AcceptedByUserID uuid.NullUUID
	AcceptedAt       pgtype.Timestamptz
	CreatedAt        time.Time
}

func (q *Queries) ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]ListInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listInvitations,
		arg.OrganizationID,
		arg.Status,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsRow{}
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.RoleCode,
			&i.Status,
			&i.ExpiresAt,
			&i.InvitedByUserID,
			&i.AcceptedByUserID,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :exec
update core.invitations set status = 'revoked'
where organization_id = $1 and id = $2 and status = 'pending'
`

type RevokeInvitationParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) error {
	_, err := q.db.Exec(ctx, revokeInvitation, arg.OrganizationID, arg.ID)
	return err
}
