// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findActiveUserIDBySubject = `-- name: FindActiveUserIDBySubject :one

select id from core.find_user_by_subject($1::text) where status = 'active'
`

// La sesión ya debe tener app.current_user_id (políticas organization_users_own / organization_user_roles_own).
func (q *Queries) FindActiveUserIDBySubject(ctx context.Context, externalSubject string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findActiveUserIDBySubject, externalSubject)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getActiveMembership = `-- name: GetActiveMembership :one
select u.id as user_id,
       coalesce(array_agg(r.role_code order by r.role_code) filter (where r.role_code is not null), '{}')::text[] as roles
from core.users u
join core.organization_users ou
  on ou.user_id = u.id and ou.organization_id = $1 and ou.status = 'active'
join core.organizations o
  on o.id = ou.organization_id and o.status = 'active'
left join core.organization_user_roles r
  on r.organization_id = ou.organization_id and r.organization_user_id = ou.id
where u.id = $2
group by u.id
`

type GetActiveMembershipParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

type GetActiveMembershipRow struct {
	UserID uuid.UUID
	Roles  []string
}

func (q *Queries) GetActiveMembership(ctx context.Context, arg GetActiveMembershipParams) (GetActiveMembershipRow, error) {
	row := q.db.QueryRow(ctx, getActiveMembership, arg.OrganizationID, arg.UserID)
	var i GetActiveMembershipRow
	err := row.Scan(&i.UserID, &i.Roles)
	return i, err
}

const insertMembership = `-- name: InsertMembership :one
insert into core.organization_users (organization_id, user_id) values ($1, $2) returning id
`

type InsertMembershipParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertMembership, arg.OrganizationID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertMembershipRole = `-- name: InsertMembershipRole :exec
insert into core.organization_user_roles (organization_id, organization_user_id, role_code, granted_by_user_id)
values ($1, $2, $3, $4)
`

type InsertMembershipRoleParams struct {
	OrganizationID     uuid.UUID
	OrganizationUserID uuid.UUID
	RoleCode           string
	GrantedByUserID    uuid.NullUUID
}

func (q *Queries) InsertMembershipRole(ctx context.Context, arg InsertMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, insertMembershipRole,
		arg.OrganizationID,
		arg.OrganizationUserID,
		arg.RoleCode,
		arg.GrantedByUserID,
	)
	return err
}

const listActiveMembershipsForUser = `-- name: ListActiveMembershipsForUser :many
select ou.organization_id,
       o.legal_name,
       coalesce(o.trade_name, '')::text as trade_name,
       o.status as organization_status,
       ou.status,
       ou.joined_at,
       coalesce(array_agg(r.role_code order by r.role_code) filter (where r.role_code is not null), '{}')::text[] as roles
from core.organization_users ou
join core.organizations o on o.id = ou.organization_id
left join core.organization_user_roles r
  on r.organization_id = ou.organization_id and r.organization_user_id = ou.id
where ou.user_id = $1 and ou.status = 'active'
group by ou.organization_id, o.legal_name, o.trade_name, o.status, ou.status, ou.joined_at
order by o.legal_name, ou.organization_id
`

type ListActiveMembershipsForUserRow struct {
	OrganizationID     uuid.UUID
	LegalName          string
	TradeName          string
	OrganizationStatus string
	Status             string
	JoinedAt           time.Time
	Roles              []string
}

func (q *Queries) ListActiveMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListActiveMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveMembershipsForUserRow{}
	for rows.Next() {
		var i ListActiveMembershipsForUserRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.LegalName,
			&i.TradeName,
			&i.OrganizationStatus,
			&i.Status,
			&i.JoinedAt,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
