// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveOwners = `-- name: CountActiveOwners :one
select count(*)::int
from core.organization_users ou
join core.organization_user_roles r
  on r.organization_id = ou.organization_id and r.organization_user_id = ou.id and r.role_code = 'owner'
where ou.organization_id = $1 and ou.status = 'active'
`

func (q *Queries) CountActiveOwners(ctx context.Context, organizationID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveOwners, organizationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteMembershipRoles = `-- name: DeleteMembershipRoles :exec
delete from core.organization_user_roles
where organization_id = $1 and organization_user_id = $2
`

type DeleteMembershipRolesParams struct {
	OrganizationID     uuid.UUID
	OrganizationUserID uuid.UUID
}

func (q *Queries) DeleteMembershipRoles(ctx context.Context, arg DeleteMembershipRolesParams) error {
	_, err := q.db.Exec(ctx, deleteMembershipRoles, arg.OrganizationID, arg.OrganizationUserID)
	return err
}

const findMembershipByUser = `-- name: FindMembershipByUser :one
select id, status from core.organization_users where organization_id = $1 and user_id = $2
`

type FindMembershipByUserParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

type FindMembershipByUserRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) FindMembershipByUser(ctx context.Context, arg FindMembershipByUserParams) (FindMembershipByUserRow, error) {
	row := q.db.QueryRow(ctx, findMembershipByUser, arg.OrganizationID, arg.UserID)
	var i FindMembershipByUserRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getMemberForUpdate = `-- name: GetMemberForUpdate :one
select ou.id as membership_id, u.id as user_id, u.external_subject, u.email, u.full_name, ou.status, ou.joined_at,
       coalesce((select array_agg(r.role_code order by r.role_code)
                   from core.organization_user_roles r
                  where r.organization_id = ou.organization_id and r.organization_user_id = ou.id), '{}')::text[] as roles
from core.organization_users ou
join core.users u on u.id = ou.user_id
where ou.organization_id = $1 and ou.user_id = $2
for update of ou
`

type GetMemberForUpdateParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

type GetMemberForUpdateRow struct {
	MembershipID    uuid.UUID
	UserID          uuid.UUID
	ExternalSubject string
	Email           string
	FullName        string
	Status          string
	JoinedAt        time.Time
	Roles           []string
}

// Bloquea la membresía hasta el fin de la transacción: dos admins cambiando al mismo miembro se serializan.
func (q *Queries) GetMemberForUpdate(ctx context.Context, arg GetMemberForUpdateParams) (GetMemberForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getMemberForUpdate, arg.OrganizationID, arg.UserID)
	var i GetMemberForUpdateRow
	err := row.Scan(
		&i.MembershipID,
		&i.UserID,
		&i.ExternalSubject,
		&i.Email,
		&i.FullName,
		&i.Status,
		&i.JoinedAt,
		&i.Roles,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many

select ou.id as membership_id, u.id as user_id, u.email, u.full_name, ou.status, ou.joined_at,
       coalesce(array_agg(r.role_code order by r.role_code) filter (where r.role_code is not null), '{}')::text[] as roles
from core.organization_users ou
join core.users u on u.id = ou.user_id
left join core.organization_user_roles r
  on r.organization_id = ou.organization_id and r.organization_user_id = ou.id
where ou.organization_id = $1
  and ($2::text is null or ou.status = $2::text)
  and ($3::timestamptz is null
       or (ou.joined_at, ou.id) > ($3::timestamptz, $4::uuid))
group by ou.id, u.id, u.email, u.full_name, ou.status, ou.joined_at
order by ou.joined_at, ou.id
limit $5
`

type ListMembersParams struct {
	OrganizationID uuid.UUID
	Status         pgtype.Text
	AfterJoinedAt  pgtype.Timestamptz
	AfterID        uuid.NullUUID
	PageSize       int32
}

type ListMembersRow struct {
	MembershipID uuid.UUID
	UserID       uuid.UUID
	Email        string
	FullName     string
	Status       string
	JoinedAt     time.Time
	Roles        []string
}

// Sesión con app.current_organization_id = organización activa (políticas *_tenant).
// Paginación por cursor sobre (joined_at, id): estable aunque entren miembros nuevos entre páginas.
func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers,
		arg.OrganizationID,
		arg.Status,
		arg.AfterJoinedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.UserID,
			&i.Email,
			&i.FullName,
			&i.Status,
			&i.JoinedAt,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipStatus = `-- name: UpdateMembershipStatus :exec
update core.organization_users set status = $1
where organization_id = $2 and id = $3
`

type UpdateMembershipStatusParams struct {
	Status         string
	OrganizationID uuid.UUID
	MembershipID   uuid.UUID
}

func (q *Queries) UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) error {
	_, err := q.db.Exec(ctx, updateMembershipStatus, arg.Status, arg.OrganizationID, arg.MembershipID)
	return err
}
