// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditAuditEvent struct {
	ID             uuid.UUID
	OrganizationID uuid.NullUUID
	OccurredAt     time.Time
	Service        string
	ActorType      string
	ActorUserID    uuid.NullUUID
	Action         string
	EntityType     string
	EntityID       uuid.NullUUID
	CorrelationID  uuid.UUID
	IpAddress      *netip.Addr
	UserAgent      pgtype.Text
	Payload        []byte
}

type CoreBranch struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Code           string
	Name           string
	Address        pgtype.Text
	Phone          pgtype.Text
	Email          pgtype.Text
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type CoreInvitation struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	Email            string
	RoleCode         string
	TokenHash        interface{}
	Status           string
	ExpiresAt        time.Time
	InvitedByUserID  uuid.UUID
	AcceptedByUserID uuid.NullUUID
	AcceptedAt       pgtype.Timestamptz
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// Tenant del SaaS. Toda tabla de negocio referencia su id en organization_id.
type CoreOrganization struct {
	ID                     uuid.UUID
	LegalName              string
	TradeName              pgtype.Text
	IdentificationTypeCode string
	IdentificationNumber   string
	Email                  string
	Phone                  pgtype.Text
	Timezone               string
	DefaultCurrencyCode    interface{}
	Status                 string
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type CoreOrganizationUser struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	Status         string
	JoinedAt       time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type CoreOrganizationUserRole struct {
	OrganizationID     uuid.UUID
	OrganizationUserID uuid.UUID
	RoleCode           string
	GrantedByUserID    uuid.NullUUID
	GrantedAt          time.Time
}

// Catálogo global de roles asignables dentro de una organización.
type CoreRole struct {
	Code        string
	Name        string
	Description pgtype.Text
	CreatedAt   time.Time
}

// Usuario global enlazado al proveedor de identidad OIDC (sub). Sin contraseñas.
type CoreUser struct {
	ID               uuid.UUID
	IdentityProvider string
	ExternalSubject  string
	Email            string
	FullName         string
	Status           string
	LastLoginAt      pgtype.Timestamptz
	CreatedAt        time.Time
	UpdatedAt        time.Time
	// Organización elegida por el usuario. El hook de Auth la revalida contra una membresía activa antes de emitir org_id.
	ActiveOrganizationID uuid.NullUUID
}

type IntegrationIdempotencyKey struct {
	Service        string
	OrganizationID uuid.UUID
	IdempotencyKey string
	RequestHash    interface{}
	ResponseStatus pgtype.Int4
	ResponseBody   []byte
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

type SubscriptionsOrganizationSubscription struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	PlanID             uuid.UUID
	Status             string
	StartedAt          time.Time
	EndsAt             pgtype.Timestamptz
	CurrentPeriodStart pgtype.Date
	CurrentPeriodEnd   pgtype.Date
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type SubscriptionsPlan struct {
	ID          uuid.UUID
	Code        string
	Name        string
	Description pgtype.Text
	// NULL = ilimitado.
	MonthlyDocumentLimit pgtype.Int4
	PriceAmount          interface{}
	CurrencyCode         interface{}
	IsActive             bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type SubscriptionsUsageCounter struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	SubscriptionID uuid.UUID
	MetricCode     string
	PeriodStart    pgtype.Date
	PeriodEnd      pgtype.Date
	Quantity       int64
	UpdatedAt      time.Time
}
