// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getOrganization = `-- name: GetOrganization :one
select id, legal_name, coalesce(trade_name, '')::text as trade_name, identification_type_code, identification_number,
       email, coalesce(phone, '')::text as phone, timezone, default_currency_code::text as default_currency_code,
       status, created_at, updated_at
from core.organizations where id = $1
`

type GetOrganizationRow struct {
	ID                     uuid.UUID
	LegalName              string
	TradeName              string
	IdentificationTypeCode string
	IdentificationNumber   string
	Email                  string
	Phone                  string
	Timezone               string
	DefaultCurrencyCode    string
	Status                 string
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (GetOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i GetOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TradeName,
		&i.IdentificationTypeCode,
		&i.IdentificationNumber,
		&i.Email,
		&i.Phone,
		&i.Timezone,
		&i.DefaultCurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationForUpdate = `-- name: GetOrganizationForUpdate :one
select id, legal_name, coalesce(trade_name, '')::text as trade_name, identification_type_code, identification_number,
       email, coalesce(phone, '')::text as phone, timezone, default_currency_code::text as default_currency_code,
       status, created_at, updated_at
from core.organizations where id = $1
for update
`

type GetOrganizationForUpdateRow struct {
	ID                     uuid.UUID
	LegalName              string
	TradeName              string
	IdentificationTypeCode string
	IdentificationNumber   string
	Email                  string
	Phone                  string
	Timezone               string
	DefaultCurrencyCode    string
	Status                 string
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) GetOrganizationForUpdate(ctx context.Context, id uuid.UUID) (GetOrganizationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationForUpdate, id)
	var i GetOrganizationForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TradeName,
		&i.IdentificationTypeCode,
		&i.IdentificationNumber,
		&i.Email,
		&i.Phone,
		&i.Timezone,
		&i.DefaultCurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrganization = `-- name: InsertOrganization :one

insert into core.organizations (id, legal_name, trade_name, identification_type_code, identification_number, email, phone, timezone)
values ($1, $2, nullif($3::text, ''), $4,
        $5, $6, nullif($7::text, ''), $8)
returning id, legal_name, coalesce(trade_name, '')::text as trade_name, identification_type_code, identification_number,
          email, coalesce(phone, '')::text as phone, timezone, default_currency_code::text as default_currency_code,
          status, created_at, updated_at
`

type InsertOrganizationParams struct {
	ID                     uuid.UUID
	LegalName              string
	TradeName              string
	IdentificationTypeCode string
	IdentificationNumber   string
	Email                  string
	Phone                  string
	Timezone               string
}

type InsertOrganizationRow struct {
	ID                     uuid.UUID
	LegalName              string
	TradeName              string
	IdentificationTypeCode string
	IdentificationNumber   string
	Email                  string
	Phone                  string
	Timezone               string
	DefaultCurrencyCode    string
	Status                 string
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

// Todas corren con app.current_organization_id = la organización en cuestión (políticas organizations_*).
func (q *Queries) InsertOrganization(ctx context.Context, arg InsertOrganizationParams) (InsertOrganizationRow, error) {
	row := q.db.QueryRow(ctx, insertOrganization,
		arg.ID,
		arg.LegalName,
		arg.TradeName,
		arg.IdentificationTypeCode,
		arg.IdentificationNumber,
		arg.Email,
		arg.Phone,
		arg.Timezone,
	)
	var i InsertOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TradeName,
		&i.IdentificationTypeCode,
		&i.IdentificationNumber,
		&i.Email,
		&i.Phone,
		&i.Timezone,
		&i.DefaultCurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganization = `-- name: UpdateOrganization :one
update core.organizations
set trade_name = nullif($1::text, ''), email = $2,
    phone = nullif($3::text, ''), timezone = $4
where id = $5
returning id, legal_name, coalesce(trade_name, '')::text as trade_name, identification_type_code, identification_number,
          email, coalesce(phone, '')::text as phone, timezone, default_currency_code::text as default_currency_code,
          status, created_at, updated_at
`

type UpdateOrganizationParams struct {
	TradeName string
	Email     string
	Phone     string
	Timezone  string
	ID        uuid.UUID
}

type UpdateOrganizationRow struct {
	ID                     uuid.UUID
	LegalName              string
	TradeName              string
	IdentificationTypeCode string
	IdentificationNumber   string
	Email                  string
	Phone                  string
	Timezone               string
	DefaultCurrencyCode    string
	Status                 string
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (UpdateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.TradeName,
		arg.Email,
		arg.Phone,
		arg.Timezone,
		arg.ID,
	)
	var i UpdateOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TradeName,
		&i.IdentificationTypeCode,
		&i.IdentificationNumber,
		&i.Email,
		&i.Phone,
		&i.Timezone,
		&i.DefaultCurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
