// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findUserBySubject = `-- name: FindUserBySubject :one

select id, external_subject, email, full_name, status, active_organization_id, created_at
from core.find_user_by_subject($1::text)
`

type FindUserBySubjectRow struct {
	ID                   uuid.UUID
	ExternalSubject      string
	Email                string
	FullName             string
	Status               string
	ActiveOrganizationID uuid.NullUUID
	CreatedAt            time.Time
}

// core.users no es visible sin sesión de usuario (políticas users_self / users_org_members, migración 00005).
// La búsqueda por sujeto y el alta pasan por funciones security definer.
func (q *Queries) FindUserBySubject(ctx context.Context, externalSubject string) (FindUserBySubjectRow, error) {
	row := q.db.QueryRow(ctx, findUserBySubject, externalSubject)
	var i FindUserBySubjectRow
	err := row.Scan(
		&i.ID,
		&i.ExternalSubject,
		&i.Email,
		&i.FullName,
		&i.Status,
		&i.ActiveOrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const insertUserIfAbsent = `-- name: InsertUserIfAbsent :one
select id, external_subject, email, full_name, status, active_organization_id, created_at
from core.provision_user($1::text, $2::text, $3::text)
`

type InsertUserIfAbsentParams struct {
	ExternalSubject string
	Email           string
	FullName        string
}

type InsertUserIfAbsentRow struct {
	ID                   uuid.UUID
	ExternalSubject      string
	Email                string
	FullName             string
	Status               string
	ActiveOrganizationID uuid.NullUUID
	CreatedAt            time.Time
}

// Alta idempotente: ante llamadas concurrentes del mismo sujeto, solo una inserta; las demás no devuelven fila
// y el caso de uso relee. Un email ya usado por otra identidad sigue fallando por users_email_uk (409).
func (q *Queries) InsertUserIfAbsent(ctx context.Context, arg InsertUserIfAbsentParams) (InsertUserIfAbsentRow, error) {
	row := q.db.QueryRow(ctx, insertUserIfAbsent, arg.ExternalSubject, arg.Email, arg.FullName)
	var i InsertUserIfAbsentRow
	err := row.Scan(
		&i.ID,
		&i.ExternalSubject,
		&i.Email,
		&i.FullName,
		&i.Status,
		&i.ActiveOrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const setUserActiveOrganization = `-- name: SetUserActiveOrganization :execrows
update core.users set active_organization_id = $1
where id = $2
`

type SetUserActiveOrganizationParams struct {
	OrganizationID uuid.NullUUID
	UserID         uuid.UUID
}

// Requiere la sesión del propio usuario (users_self_update).
func (q *Queries) SetUserActiveOrganization(ctx context.Context, arg SetUserActiveOrganizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserActiveOrganization, arg.OrganizationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
